#!/usr/bin/env python3
"""build_data.py -- turn the data files under data/ into C tables.

The game data is hand-written, in four line-oriented files under data/. This
reads them and writes the four src/gen_*.c files the program compiles. The C
is generated so that adding a race or a magic item means editing one text
line, not finding the right initialiser in the right table.

Nothing here reads the OCR dumps in TextFiles/. Those are kept only so
tools/audit.py can check what is written here against the books.

Every cross-reference is resolved by name -- a feature names its class, a
subrace names its race -- and an unresolved name is an error that stops the
run before anything is written. That replaces the checking the compiler used
to do when the tables were C.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
SRC = os.path.join(ROOT, "src")

# ---------------------------------------------------------------- the format


class Rec:
    """One record: its tag, its fields, and where it came from."""

    def __init__(self, tag, fields, where):
        self.tag = tag
        self.f = fields
        self.where = where

    def str(self, i):
        if i >= len(self.f):
            self.die("expected at least %d fields, found %d" % (i + 1,
                                                                len(self.f)))
        return self.f[i]

    def int(self, i):
        s = self.str(i).strip()
        try:
            return int(s)
        except ValueError:
            self.die("field %d: expected a number, found %r" % (i + 1, s))

    def die(self, msg):
        sys.exit("%s: %s: %s" % (self.where, self.tag, msg))


def split_fields(line):
    """Split on '|', honouring the '\\|' and '\\\\' escapes."""
    out, cur, i = [], [], 0
    while i < len(line):
        c = line[i]
        if c == "\\" and i + 1 < len(line):
            cur.append(line[i + 1])
            i += 2
        elif c == "|":
            out.append("".join(cur))
            cur = []
            i += 1
        else:
            cur.append(c)
            i += 1
    out.append("".join(cur))
    return out


def read_file(name):
    """Records from one data file, in the order they appear."""
    path = os.path.join(DATA, name)
    if not os.path.exists(path):
        sys.exit("build_data: missing %s" % path)

    recs, pending, start = [], None, 0
    for n, raw in enumerate(open(path, encoding="utf-8"), 1):
        line = raw.rstrip("\n").rstrip("\r")
        if pending is None and (not line.strip() or line.lstrip()[0] == "#"):
            continue
        # A line ending in an odd number of backslashes continues; the last
        # one is the continuation mark and the rest are escapes.
        trail = len(line) - len(line.rstrip("\\"))
        if trail % 2 == 1:
            line = line[:-1]
            if pending is None:
                pending, start = line, n
            else:
                pending += line
            continue
        if pending is not None:
            line, pending = pending + line, None
        else:
            start = n
        fields = split_fields(line)
        recs.append(Rec(fields[0], fields[1:], "%s:%d" % (name, start)))
    if pending is not None:
        sys.exit("%s:%d: file ends in a continuation" % (name, start))
    return recs


def by_tag(recs):
    out = {}
    for r in recs:
        out.setdefault(r.tag, []).append(r)
    return out


# ------------------------------------------------------------ writing the C


def cstr(s, indent=6):
    """A C string literal, wrapped at word boundaries so it stays readable."""
    esc = s.replace("\\", "\\\\").replace('"', '\\"')
    if len(esc) <= 60:
        return '"%s"' % esc
    parts, cur = [], ""
    for word in esc.split(" "):
        if cur and len(cur) + len(word) + 1 > 60:
            parts.append(cur + " ")
            cur = word
        else:
            cur = (cur + " " + word) if cur else word
    parts.append(cur)
    pad = "\n" + " " * indent
    return pad.join('"%s"' % p for p in parts)


class Out:
    def __init__(self, path, source, note=""):
        self.path = path
        self.buf = []
        self.w("/* %s -- generated from %s by tools/build_data.py.\n"
               " *\n"
               " * Do not edit this file: edit %s and run `make data`.%s\n"
               " */\n" % (os.path.basename(path), source, source,
                          ("\n *\n * " + note) if note else ""))

    def w(self, s):
        self.buf.append(s)

    def table(self, decl, rows, count_name=None):
        self.w("\n%s = {\n" % decl)
        for r in rows:
            self.w("%s,\n" % r)
        self.w("};\n")
        if count_name:
            name = decl.split("[")[0].split()[-1]
            self.w("const int %s =\n    (int)(sizeof(%s) / sizeof(%s[0]));\n"
                   % (count_name, name, name))

    def save(self):
        text = "".join(self.buf)
        old = None
        if os.path.exists(self.path):
            old = open(self.path, encoding="utf-8").read()
        if old != text:
            open(self.path, "w", encoding="utf-8").write(text)
            print("wrote %s" % os.path.relpath(self.path, ROOT))
        else:
            print("%s unchanged" % os.path.relpath(self.path, ROOT))


# ------------------------------------------------------------------- naming

BOOKS = {"PHB": "BOOK_PHB", "XGE": "BOOK_XGE", "TCE": "BOOK_TCE",
         "DMG": "BOOK_DMG", "MPMM": "BOOK_MPMM", "MM": "BOOK_MM",
         "SCAG": "BOOK_SCAG", "Homebrew": "BOOK_HOMEBREW"}

ABILITIES = {"STR": "ABL_STR", "DEX": "ABL_DEX", "CON": "ABL_CON",
             "INT": "ABL_INT", "WIS": "ABL_WIS", "CHA": "ABL_CHA",
             "-": "ABL_COUNT"}

SKILLS = {
    "Acrobatics": "SKL_ACROBATICS", "Animal Handling": "SKL_ANIMAL_HANDLING",
    "Arcana": "SKL_ARCANA", "Athletics": "SKL_ATHLETICS",
    "Deception": "SKL_DECEPTION", "History": "SKL_HISTORY",
    "Insight": "SKL_INSIGHT", "Intimidation": "SKL_INTIMIDATION",
    "Investigation": "SKL_INVESTIGATION", "Medicine": "SKL_MEDICINE",
    "Nature": "SKL_NATURE", "Perception": "SKL_PERCEPTION",
    "Performance": "SKL_PERFORMANCE", "Persuasion": "SKL_PERSUASION",
    "Religion": "SKL_RELIGION", "Sleight of Hand": "SKL_SLEIGHT_OF_HAND",
    "Stealth": "SKL_STEALTH", "Survival": "SKL_SURVIVAL",
    "-": "SKL_COUNT",           # the background lets you choose this one
}

SIZES = {"Small": "SZ_SMALL", "Medium": "SZ_MEDIUM"}

CASTERS = {"none": "CAST_NONE", "full": "CAST_FULL", "half": "CAST_HALF",
           "third": "CAST_THIRD", "pact": "CAST_PACT"}

PREPS = {"none": "PREP_NONE", "known": "PREP_KNOWN",
         "prepared": "PREP_PREPARED", "spellbook": "PREP_SPELLBOOK"}

CATEGORIES = {
    "light-armour": "ITEM_LIGHT_ARMOR", "medium-armour": "ITEM_MEDIUM_ARMOR",
    "heavy-armour": "ITEM_HEAVY_ARMOR", "shield": "ITEM_SHIELD",
    "simple-melee": "ITEM_SIMPLE_MELEE", "simple-ranged": "ITEM_SIMPLE_RANGED",
    "martial-melee": "ITEM_MARTIAL_MELEE",
    "martial-ranged": "ITEM_MARTIAL_RANGED", "gear": "ITEM_GEAR",
    "tool": "ITEM_TOOL", "pack": "ITEM_PACK", "mount": "ITEM_MOUNT",
}

SPELL_CLASS_BITS = {
    "bard": "SPL_BARD", "cleric": "SPL_CLERIC", "druid": "SPL_DRUID",
    "paladin": "SPL_PALADIN", "ranger": "SPL_RANGER",
    "sorcerer": "SPL_SORCERER", "warlock": "SPL_WARLOCK",
    "wizard": "SPL_WIZARD", "artificer": "SPL_ARTIFICER",
}


def lookup(table, rec, i, what):
    key = rec.str(i)
    if key not in table:
        rec.die("field %d: unknown %s %r" % (i + 1, what, key))
    return table[key]


# --------------------------------------------------------------- assembling


class Progressions:
    """The per-level tables classes and option lists point at.

    Each is written once as a static array; anything that needs one refers to
    it by the key its PROGRESSION line carries.
    """

    def __init__(self):
        self.by_key = {}
        self.arrays = []        # (name, values, key)

    def add(self, rec):
        key = rec.str(0)
        vals = [v.strip() for v in rec.str(1).split(",")]
        if len(vals) != 21:
            rec.die("%r has %d levels, expected 21" % (key, len(vals)))
        if key in self.by_key:
            rec.die("%r is defined twice" % key)
        name = "PROG_%d" % len(self.arrays)
        self.by_key[key] = name
        self.arrays.append((name, [int(v) for v in vals], key))
        return name

    def name(self, key, rec):
        if key not in self.by_key:
            rec.die("no PROGRESSION named %r" % key)
        return self.by_key[key]

    # A few progressions are named in data.h and read directly by the rules
    # engine, so they are written under those names instead of a numbered
    # static one.
    PUBLIC = {"infusions known": "INFUSIONS_KNOWN",
              "infused items": "INFUSED_ITEMS"}

    def emit(self, out):
        out.w("\n/* Per-level progressions, one number for each of levels 0"
              " to 20. */\n")
        for name, vals, key in self.arrays:
            public = self.PUBLIC.get(key)
            body = ", ".join(str(v) for v in vals)
            if public:
                self.by_key[key] = public
                out.w("const unsigned char %s[MAX_LEVEL + 1] = {\n"
                      "    %s\n};\n" % (public, body))
            else:
                out.w("/* %s */\n"
                      "static const unsigned char %s[MAX_LEVEL + 1] = {\n"
                      "    %s\n};\n" % (key, name, body))


def unique_named(store, values, prefix, kind):
    """One static array per distinct value list, shared where they match."""
    key = tuple(values)
    if key not in store:
        store[key] = ("%s_%d" % (prefix, len(store)), values, kind)
    return store[key][0]


# ---------------------------------------------------------------- character


def build_character():
    recs = read_file("character.txt")
    tags = by_tag(recs)
    out = Out(os.path.join(SRC, "gen_character.c"), "data/character.txt")
    out.w('#include "data.h"\n')

    # --- languages
    out.table("const LanguageData LANGUAGES[]",
              ["    { %s, %s }" % (cstr(r.str(0)), lookup(BOOKS, r, 1, "book"))
               for r in tags.get("LANGUAGE", [])],
              "LANGUAGE_COUNT")

    # --- subraces, grouped under the race that owns them
    subraces = tags.get("SUBRACE", [])
    rows, window = [], {}
    for r in subraces:
        race = r.str(0)
        if race in window and window[race][1] != len(rows):
            r.die("subraces of %r are not written together" % race)
        first, _ = window.get(race, (len(rows), 0))
        window[race] = (first, len(rows) + 1)
        rows.append(
            "    { %s, %s, {%s}, %d, %d, %d, %d, %d, %d, %d,\n      %s }"
            % (cstr(r.str(1)), lookup(BOOKS, r, 2, "book"),
               ",".join(str(r.int(3 + k)) for k in range(6)),
               r.int(9), r.int(10), r.int(11), r.int(12), r.int(13),
               r.int(14), r.int(15), cstr(r.str(16))))
    out.table("const SubraceData SUBRACES[]", rows, "SUBRACE_COUNT")

    # --- races
    rows = []
    race_names = set()
    for r in tags.get("RACE", []):
        name = r.str(0)
        race_names.add(name)
        first, last = window.get(name, (0, 0))
        count = (last - first) if name in window else 0
        rows.append(
            "    { %s, %s, {%s}, %d, %s, %d,\n      %s, %d, %d, %d, %d, %d,"
            " %d, %d, %d,\n      %s, %d }"
            % (cstr(r.str(0)), lookup(BOOKS, r, 1, "book"),
               ",".join(str(r.int(2 + k)) for k in range(6)),
               r.int(8), lookup(SIZES, r, 9, "size"), r.int(10),
               cstr(r.str(11)), r.int(12), r.int(13), r.int(14), r.int(15),
               r.int(16), r.int(17), first, count,
               cstr(r.str(19)), r.int(18)))
    out.table("const RaceData RACES[]", rows, "RACE_COUNT")
    for r in subraces:
        if r.str(0) not in race_names:
            r.die("no RACE named %r" % r.str(0))

    # --- the Random Height and Weight table
    rows = []
    for r in tags.get("BODY", []):
        if r.str(0) not in race_names:
            r.die("no RACE named %r" % r.str(0))
        rows.append("    { %s, %s, %d, %s, %d, %s }"
                    % (cstr(r.str(0)), cstr(r.str(1)), r.int(2),
                       cstr(r.str(3)), r.int(4), cstr(r.str(5))))
    out.table("const BodyData BODIES[]", rows, "BODY_COUNT")

    # --- draconic ancestry
    out.table("const AncestryData ANCESTRIES[]",
              ["    { %s, %s, %s }" % (cstr(r.str(0)), cstr(r.str(1)),
                                       cstr(r.str(2)))
               for r in tags.get("ANCESTRY", [])],
              "ANCESTRY_COUNT")

    # --- progressions, and the ones with names of their own
    progs = Progressions()
    for r in tags.get("PROGRESSION", []):
        progs.add(r)
    progs.emit(out)

    for key, decl in (("third-caster cantrips", "THIRD_CANTRIPS"),
                      ("third-caster spells known", "THIRD_SPELLS_KNOWN")):
        out.w("\nconst unsigned char *const %s = %s;\n"
              % (decl, progs.name(key, recs[0])))
    for key in Progressions.PUBLIC:
        progs.name(key, recs[0])

    # --- spell slots
    slots = {}
    for r in tags.get("FULLSLOTS", []):
        slots[r.int(0)] = [r.int(1 + k) for k in range(9)]
    rows = []
    for lvl in range(21):
        if lvl not in slots:
            sys.exit("data/character.txt: FULLSLOTS is missing level %d" % lvl)
        rows.append("    { 0, %s }" % ", ".join(str(v) for v in slots[lvl]))
    out.table("const unsigned char FULL_SLOTS[MAX_LEVEL + 1][10]", rows)

    pact = {}
    for r in tags.get("PACTSLOTS", []):
        pact[r.int(0)] = (r.int(1), r.int(2))
    rows = []
    for lvl in range(21):
        if lvl not in pact:
            sys.exit("data/character.txt: PACTSLOTS is missing level %d" % lvl)
        rows.append("    { %d, %d }" % pact[lvl])
    out.table("const unsigned char PACT_SLOTS[MAX_LEVEL + 1][2]", rows)

    xp = {}
    for r in tags.get("XP", []):
        xp[r.int(0)] = r.int(1)
    for lvl in range(1, 21):
        if lvl not in xp:
            sys.exit("data/character.txt: XP is missing level %d" % lvl)
    out.w("\n/* The experience needed for each level (PHB p.15). */\n"
          "const int XP_FOR_LEVEL[MAX_LEVEL + 1] = {\n    0")
    for lvl in range(1, 21):
        out.w("%s%d" % (",\n    " if lvl % 5 == 1 else ", ", xp[lvl]))
    out.w("\n};\n")

    # --- classes
    skill_lists = {}
    class_rows, class_names = [], []
    for r in tags.get("CLASS", []):
        name = r.str(0)
        class_names.append(name)
        picks = [s.strip() for s in r.str(8).split(",") if s.strip()]
        for s in picks:
            if s not in SKILLS:
                r.die("unknown skill %r" % s)
        arr = unique_named(skill_lists, [SKILLS[s] for s in picks],
                           "SKILLOPT", "Skill")
        mc = [p.strip() for p in r.str(15).split(",") if p.strip()]
        req, score = [], []
        for part in mc:
            bits = part.split()
            if len(bits) != 2 or bits[0] not in ABILITIES:
                r.die("mc_req %r should read like 'STR 13'" % part)
            req.append(ABILITIES[bits[0]])
            score.append(int(bits[1]))
        while len(req) < 2:
            req.append("ABL_COUNT")
            score.append(0)
        cantrips = "%s cantrips" % name
        known = "%s spells known" % name
        class_rows.append(
            "    { %s, %s, %d, {%s, %s},\n      %s,\n      %s,\n      %s,\n"
            "      %s, (int)(sizeof(%s) / sizeof(%s[0])), %d,\n"
            "      %s, %s, %s,\n      %d, %s, 0, 0,\n"
            "      {%s, %s}, {%d, %d}, %d, %d,\n      %s, %d, %d,\n"
            "      %s, %s,\n      %s,\n      %s,\n      %d, %d }"
            % (cstr(name), lookup(BOOKS, r, 1, "book"), r.int(2),
               lookup(ABILITIES, r, 3, "ability"),
               lookup(ABILITIES, r, 4, "ability"),
               cstr(r.str(5)), cstr(r.str(6)), cstr(r.str(7)),
               arr, arr, arr, r.int(9),
               lookup(CASTERS, r, 10, "caster type"),
               lookup(PREPS, r, 11, "preparation style"),
               lookup(ABILITIES, r, 12, "ability"),
               r.int(13), cstr(r.str(14)),
               req[0], req[1], score[0], score[1], len(mc), r.int(16),
               cstr(r.str(17)), r.int(18), r.int(19),
               progs.by_key.get(cantrips, "NULL"),
               progs.by_key.get(known, "NULL"),
               cstr(r.str(20)), cstr(r.str(21)), r.int(22), r.int(23)))

    out.w("\n/* The skills each class may pick from. Classes with the same"
          " list share one\n   array. */\n")
    for _, (arr, vals, kind) in sorted(skill_lists.items(),
                                       key=lambda kv: kv[1][0]):
        out.w("static const %s %s[] = {\n    %s\n};\n"
              % (kind, arr, ", ".join(vals)))
    out.table("const ClassData CLASSES[]", class_rows, "CLASS_COUNT")

    def class_index(rec, i):
        name = rec.str(i)
        if name not in class_names:
            rec.die("no CLASS named %r" % name)
        return class_names.index(name)

    # --- subclasses
    rows, subclass_names = [], []
    for r in tags.get("SUBCLASS", []):
        subclass_names.append(r.str(1))
        rows.append(
            "    { %d, %s, %s,\n      %s,\n      %s,\n      %s, %s }"
            % (class_index(r, 0), lookup(BOOKS, r, 2, "book"),
               cstr(r.str(1)), cstr(r.str(3)), cstr(r.str(4)),
               cstr(r.str(5)), cstr(r.str(6))))
    out.table("const SubclassData SUBCLASSES[]", rows, "SUBCLASS_COUNT")

    # --- features
    rows = []
    for r in tags.get("FEATURE", []):
        sub = r.str(1)
        if sub and sub not in subclass_names:
            r.die("no SUBCLASS named %r" % sub)
        rows.append(
            "    { %d, %d, %d, %s,\n      %s }"
            % (class_index(r, 0),
               subclass_names.index(sub) if sub else -1,
               r.int(2), cstr(r.str(3)), cstr(r.str(4))))
    out.table("const FeatureData FEATURES[]", rows, "FEATURE_COUNT")

    # --- Tasha's optional class features
    out.table(
        "const OptionalFeature OPTIONAL_FEATURES[]",
        ["    { %d, %s, %d, %s,\n      %s,\n      %s }"
         % (class_index(r, 0), lookup(BOOKS, r, 1, "book"), r.int(2),
            cstr(r.str(3)), cstr(r.str(4)), cstr(r.str(5)))
         for r in tags.get("OPTFEATURE", [])],
        "OPTIONAL_FEATURE_COUNT")

    out.table(
        "const AdditionalSpells ADDITIONAL_SPELLS[]",
        ["    { %d,\n      %s }" % (class_index(r, 0), cstr(r.str(1)))
         for r in tags.get("ADDSPELLS", [])],
        "ADDITIONAL_SPELLS_COUNT")

    styles = {}
    for r in tags.get("FIGHTINGSTYLES", []):
        class_index(r, 0)
        styles[r.str(0)] = r.str(1)
    for who in ("Fighter", "Paladin", "Ranger"):
        if who not in styles:
            sys.exit("data/character.txt: no FIGHTINGSTYLES for the %s" % who)
        out.w("\nconst char *const TASHA_%s_STYLES =\n    %s;\n"
              % (who.upper(), cstr(styles[who], 4)))

    out.table(
        "const OptionSpells OPTION_SPELLS[]",
        ["    { %s,\n      %s,\n      %s,\n      %s }"
         % (cstr(r.str(0)), cstr(r.str(1)), cstr(r.str(2)), cstr(r.str(3)))
         for r in tags.get("OPTIONSPELLS", [])],
        "OPTION_SPELLS_COUNT")
    for r in tags.get("OPTIONSPELLS", []):
        if r.str(0) not in subclass_names:
            r.die("no SUBCLASS named %r" % r.str(0))

    out.table(
        "const InfusionData INFUSIONS[]",
        ["    { %s, %s, %d,\n      %s,\n      %s }"
         % (cstr(r.str(0)), cstr(r.str(1)), r.int(2), cstr(r.str(3)),
            cstr(r.str(4)))
         for r in tags.get("INFUSION", [])],
        "INFUSION_COUNT")

    # --- the lists a class picks from as it levels
    options = {}
    for r in tags.get("OPTION", []):
        options.setdefault(r.str(0), []).append(r)
    lists = tags.get("OPTIONLIST", [])
    out.w("\n/* What a class chooses from as it levels. */\n")
    for n, r in enumerate(lists):
        key = r.str(0)
        if key not in options:
            r.die("no OPTION lines belong to %r" % key)
        out.w("static const ClassOption OPTS_%d[] = {\n" % n)
        for o in options[key]:
            out.w("    { %s, %s, %d, %s,\n      %s },\n"
                  % (cstr(o.str(1)), lookup(BOOKS, o, 2, "book"), o.int(3),
                     cstr(o.str(4)), cstr(o.str(5))))
        out.w("};\n")
    seen = set(r.str(0) for r in lists)
    for key, rs in options.items():
        if key not in seen:
            rs[0].die("no OPTIONLIST named %r" % key)

    rows = []
    for n, r in enumerate(lists):
        rows.append(
            "    { %s, %s,\n      %s, %s,\n"
            "      OPTS_%d, (int)(sizeof(OPTS_%d) / sizeof(OPTS_%d[0])),\n"
            "      %s, %d }"
            % (cstr(r.str(1)), cstr(r.str(2)), cstr(r.str(3)),
               cstr(r.str(4)), n, n, n, progs.name(r.str(0), r), r.int(5)))
    out.table("const OptionList OPTION_LISTS[]", rows, "OPTION_LIST_COUNT")

    # --- backgrounds, with their suggested traits
    lists = {"BGTRAIT": (8, {}), "BGIDEAL": (6, {}), "BGBOND": (6, {}),
             "BGFLAW": (6, {})}
    for tag, (cap, store) in lists.items():
        for r in tags.get(tag, []):
            store.setdefault(r.str(0), []).append((r, r.str(1)))
    rows, bg_names = [], []
    for r in tags.get("BACKGROUND", []):
        name = r.str(0)
        bg_names.append(name)
        parts = []
        for tag in ("BGTRAIT", "BGIDEAL", "BGBOND", "BGFLAW"):
            cap, store = lists[tag]
            got = store.get(name, [])
            if len(got) > cap:
                got[cap][0].die("%s takes at most %d entries" % (tag, cap))
            texts = ["      " + cstr(t, 8) for _, t in got]
            texts += ["      NULL"] * (cap - len(got))
            parts.append("    {\n" + ",\n".join(texts) + "\n    }")
        rows.append(
            "    { %s, %s,\n      { %s, %s }, %d, %s,\n      %s, %d,\n"
            "      %s,\n      %d, %s,\n      %s,\n%s\n    }"
            % (cstr(name), lookup(BOOKS, r, 1, "book"),
               lookup(SKILLS, r, 2, "skill"), lookup(SKILLS, r, 3, "skill"),
               r.int(4), cstr(r.str(5)),
               cstr(r.str(6)), r.int(7), cstr(r.str(8)), r.int(9),
               cstr(r.str(10)), cstr(r.str(11)),
               ",\n".join(parts)))
    out.table("const BackgroundData BACKGROUNDS[]", rows, "BACKGROUND_COUNT")
    for tag, (_, store) in lists.items():
        for name, got in store.items():
            if name not in bg_names:
                got[0][0].die("no BACKGROUND named %r" % name)

    # --- feats
    rows = []
    for r in tags.get("FEAT", []):
        rows.append(
            "    { %s, %s,\n      %s,\n      %s, %s, %d, %s, %d,\n"
            "      {%s}, %d, %s,\n      %s,\n      %s }"
            % (cstr(r.str(0)), lookup(BOOKS, r, 1, "book"), cstr(r.str(2)),
               lookup(ABILITIES, r, 3, "ability"),
               lookup(ABILITIES, r, 4, "ability"), r.int(5), cstr(r.str(6)),
               r.int(7), ",".join(str(r.int(8 + k)) for k in range(6)),
               r.int(14), cstr(r.str(15)), cstr(r.str(17)), cstr(r.str(16))))
    out.table("const FeatData FEATS[]", rows, "FEAT_COUNT")

    out.save()
    return class_names, subclass_names


# ---------------------------------------------------------------- equipment


def build_equipment():
    tags = by_tag(read_file("equipment.txt"))
    out = Out(os.path.join(SRC, "gen_equipment.c"), "data/equipment.txt")
    out.w('#include "data.h"\n')

    rows, item_names = [], set()
    for r in tags.get("ITEM", []):
        item_names.add(r.str(0))
        rows.append(
            "    { %s, %s, %s,\n      %d, %d, %d, %d, %d, %d,\n"
            "      %s, %s, %s,\n      %s }"
            % (cstr(r.str(0)), lookup(BOOKS, r, 1, "book"),
               lookup(CATEGORIES, r, 2, "category"), r.int(3), r.int(4),
               r.int(5), r.int(6), r.int(7), r.int(8), cstr(r.str(9)),
               cstr(r.str(10)), cstr(r.str(11)), cstr(r.str(12))))
    out.table("const ItemData BOOK_ITEMS[]", rows, "BOOK_ITEM_COUNT")
    out.w("\n/* Until homebrew.c says otherwise, the bank is just the"
          " book. */\n"
          "const ItemData *ITEMS = BOOK_ITEMS;\n"
          "int ITEM_COUNT = (int)(sizeof(BOOK_ITEMS) / sizeof(BOOK_ITEMS[0]));"
          "\n")

    out.table(
        "const ItemNote ITEM_NOTES[]",
        ["    { %s,\n      %s }" % (cstr(r.str(0)), cstr(r.str(1)))
         for r in tags.get("ITEMNOTE", [])],
        "ITEM_NOTE_COUNT")
    for r in tags.get("ITEMNOTE", []):
        if r.str(0) not in item_names:
            r.die("no ITEM named %r" % r.str(0))

    out.table(
        "const ItemNote WEAPON_PROPERTIES[]",
        ["    { %s,\n      %s }" % (cstr(r.str(0)), cstr(r.str(1)))
         for r in tags.get("WEAPONPROP", [])],
        "WEAPON_PROPERTY_COUNT")

    out.table(
        "const PackItem PACK_ITEMS[]",
        ["    { %s, %s, %d }" % (cstr(r.str(0)), cstr(r.str(1)), r.int(2))
         for r in tags.get("PACKITEM", [])],
        "PACK_ITEM_COUNT")
    for r in tags.get("PACKITEM", []):
        if r.str(0) not in item_names:
            r.die("no ITEM named %r" % r.str(0))
        if r.str(1) not in item_names:
            r.die("no ITEM named %r" % r.str(1))
        if r.int(2) < 1:
            r.die("a pack cannot hold %d of something" % r.int(2))

    out.table(
        "const ToolGroup TOOL_GROUPS[]",
        ["    { %s, %s }" % (cstr(r.str(0)), cstr(r.str(1)))
         for r in tags.get("TOOLGROUP", [])],
        "TOOL_GROUP_COUNT")
    for r in tags.get("TOOLGROUP", []):
        if r.str(1) not in item_names:
            r.die("no ITEM named %r" % r.str(1))

    out.table("const char *const TRINKETS[]",
              ["    " + cstr(r.str(0)) for r in tags.get("TRINKET", [])],
              "TRINKET_COUNT")

    out.table(
        "const Lifestyle LIFESTYLES[]",
        ["    { %s, %d,\n      %s }" % (cstr(r.str(0)), r.int(1),
                                        cstr(r.str(2)))
         for r in tags.get("LIFESTYLE", [])],
        "LIFESTYLE_COUNT")

    out.table("const PriceEntry SERVICES[]",
              ["    { %s, %d }" % (cstr(r.str(0)), r.int(1))
               for r in tags.get("SERVICE", [])],
              "SERVICE_COUNT")

    out.table("const PriceEntry SPELLCASTING_SERVICES[]",
              ["    { %s, %d }" % (cstr(r.str(0)), r.int(1))
               for r in tags.get("SPELLSERVICE", [])],
              "SPELLCASTING_SERVICE_COUNT")

    out.table("const GemData GEMS[]",
              ["    { %s, %d, %s }" % (cstr(r.str(0)), r.int(1),
                                       cstr(r.str(2)))
               for r in tags.get("GEM", [])],
              "GEM_COUNT")

    rows, magic_names = [], set()
    for r in tags.get("MAGICITEM", []):
        magic_names.add(r.str(0))
        att = r.str(4)
        curse = r.str(6) if len(r.f) > 6 else ""
        rows.append(
            "    { %s, %s,\n      %s, %s,\n      %s,\n      %s,\n      %s }"
            % (cstr(r.str(0)), lookup(BOOKS, r, 1, "book"), cstr(r.str(2)),
               cstr(r.str(3)), cstr(att) if att else "NULL",
               cstr(r.str(5)), cstr(curse) if curse else "NULL"))
    out.table("const MagicItem BOOK_MAGIC_ITEMS[]", rows,
              "BOOK_MAGIC_ITEM_COUNT")
    out.w("\nconst MagicItem *MAGIC_ITEMS = BOOK_MAGIC_ITEMS;\n"
          "int MAGIC_ITEM_COUNT =\n"
          "    (int)(sizeof(BOOK_MAGIC_ITEMS) /"
          " sizeof(BOOK_MAGIC_ITEMS[0]));\n")

    # The rule rows name only the fields the item changes, so they are
    # written as designated initialisers and everything else stays zero.
    INT_KEYS = ("ac_bonus", "save_bonus", "check_bonus", "armor_base",
                "armor_dex",
                "armor_str", "armor_stealth", "shield", "only_unarmored",
                "worn",
                "unarmored_base", "variable", "weapon", "weapon_plus",
                "sets_ability",
                "sets_to",
                "sets_speed", "fly_speed", "swim_speed", "climb_speed",
                "vulnerable_others")
    rows = []
    for r in tags.get("MAGICRULE", []):
        if r.str(0) not in magic_names:
            r.die("no MAGICITEM named %r" % r.str(0))
        parts = []
        for setting in r.f[1:]:
            setting = setting.strip()
            if not setting:
                continue
            if "=" not in setting:
                r.die("%r should read like 'ac_bonus=1'" % setting)
            key, val = setting.split("=", 1)
            key = key.strip()
            if key in INT_KEYS:
                try:
                    parts.append(".%s = %d" % (key, int(val)))
                except ValueError:
                    r.die("%s wants a number, found %r" % (key, val))
            elif key in ("resist", "immune", "weapon_as"):
                parts.append(".%s = %s" % (key, cstr(val)))
            else:
                r.die("unknown setting %r" % key)
        body = ", ".join(parts)
        if len(body) > 58:
            body = ",\n      ".join(parts)
            rows.append("    { %s,\n      %s }" % (cstr(r.str(0)), body))
        else:
            rows.append("    { %s, %s }" % (cstr(r.str(0)), body))
    out.table("const MagicRule MAGIC_RULES[]", rows, "MAGIC_RULE_COUNT")

    out.save()
    return item_names, magic_names


# ------------------------------------------------------------------- spells


def build_spells():
    tags = by_tag(read_file("spells.txt"))
    out = Out(os.path.join(SRC, "gen_spells.c"), "data/spells.txt")
    out.w('#include "data.h"\n#include "data_spells.h"\n')

    schools = [r.str(0) for r in tags.get("SCHOOL", [])]
    if len(schools) != 8:
        sys.exit("data/spells.txt: expected 8 SCHOOL lines, found %d"
                 % len(schools))
    out.table("const char *const SCHOOL_NAMES[SCHOOL_COUNT]",
              ["    " + cstr(s) for s in schools])

    school_id = dict((s, "SCHOOL_" + s.upper()) for s in schools)
    rows, names = [], set()
    for r in tags.get("SPELL", []):
        if r.str(0) in names:
            r.die("%r appears twice" % r.str(0))
        names.add(r.str(0))
        bits = [c.strip() for c in r.str(10).split(",") if c.strip()]
        for c in bits:
            if c not in SPELL_CLASS_BITS:
                r.die("unknown class %r" % c)
        mask = " | ".join(SPELL_CLASS_BITS[c] for c in bits) or "0"
        rows.append(
            "    { %s, %s, %d, %s, %d, %d,\n      %s, %s,\n      %s, %s,\n"
            "      %s }"
            % (cstr(r.str(0)), lookup(BOOKS, r, 1, "book"), r.int(2),
               lookup(school_id, r, 3, "school"), r.int(4), r.int(5),
               cstr(r.str(6)), cstr(r.str(7)), cstr(r.str(8)),
               cstr(r.str(9)), mask))
    out.table("const SpellData BOOK_SPELLS[]", rows, "BOOK_SPELL_COUNT")
    out.w("\n/* Until homebrew.c says otherwise, the bank is just the"
          " book. */\n"
          "const SpellData *SPELLS = BOOK_SPELLS;\n"
          "int SPELL_COUNT =\n"
          "    (int)(sizeof(BOOK_SPELLS) / sizeof(BOOK_SPELLS[0]));\n")

    out.save()
    return names


# -------------------------------------------------------------------- world


def build_world():
    tags = by_tag(read_file("world.txt"))
    out = Out(os.path.join(SRC, "gen_world.c"), "data/world.txt")
    out.w('#include "data.h"\n')

    out.table(
        "const Deity DEITIES[]",
        ["    { %s, %s,\n      %s, %s,\n      %s, %s }"
         % (cstr(r.str(0)), cstr(r.str(1)), cstr(r.str(2)), cstr(r.str(3)),
            cstr(r.str(4)), cstr(r.str(5)))
         for r in tags.get("DEITY", [])],
        "DEITY_COUNT")

    out.table(
        "const ConditionData CONDITIONS[]",
        ["    { %s,\n      %s }" % (cstr(r.str(0)), cstr(r.str(1)))
         for r in tags.get("CONDITION", [])],
        "CONDITION_COUNT")

    sizes = [r.str(0) for r in tags.get("BEASTSIZE", [])]
    if len(sizes) != 6:
        sys.exit("data/world.txt: expected 6 BEASTSIZE lines, found %d"
                 % len(sizes))
    out.table("const char *const BEAST_SIZE_NAME[]",
              ["    " + cstr(s) for s in sizes])
    size_id = dict((s, "BSIZE_" + s.upper()) for s in sizes)

    rows = []
    for r in tags.get("BEAST", []):
        rows.append(
            "    { %s, %s, %d, %d, %d,\n      %s,\n      {%s},\n"
            "      %s, %s }"
            % (cstr(r.str(0)), lookup(size_id, r, 1, "size"), r.int(2),
               r.int(3), r.int(4), cstr(r.str(5)),
               ",".join(str(r.int(6 + k)) for k in range(6)),
               cstr(r.str(12)), cstr(r.str(13))))
    out.table("const BeastData BEASTS[]", rows, "BEAST_COUNT_ACTUAL")

    sk = [r.str(0) for r in tags.get("SIDEKICKCLASS", [])]
    if len(sk) != 3:
        sys.exit("data/world.txt: expected 3 SIDEKICKCLASS lines, found %d"
                 % len(sk))
    out.table("const char *const SIDEKICK_CLASS_NAME[SK_CLASS_COUNT]",
              ["    " + cstr(r.str(0)) for r in tags["SIDEKICKCLASS"]])
    out.table("const char *const SIDEKICK_CLASS_BLURB[SK_CLASS_COUNT]",
              ["    " + cstr(r.str(1), 4) for r in tags["SIDEKICKCLASS"]])

    roles = tags.get("SIDEKICKROLE", [])
    if len(roles) != 3:
        sys.exit("data/world.txt: expected 3 SIDEKICKROLE lines, found %d"
                 % len(roles))
    out.table("const char *const SPELLCASTER_ROLE_NAME[SK_ROLE_COUNT]",
              ["    " + cstr(r.str(0)) for r in roles])
    out.table("const char *const SPELLCASTER_ROLE_DESC[SK_ROLE_COUNT]",
              ["    " + cstr(r.str(1), 4) for r in roles])

    sk_id = dict((r.str(0), "SK_" + r.str(0).upper()) for r in sk_rows(tags))
    rows = []
    for r in tags.get("SIDEKICKFEATURE", []):
        rows.append("    { %s, %d, %s,\n      %s }"
                    % (lookup(sk_id, r, 0, "sidekick class"), r.int(1),
                       cstr(r.str(2)), cstr(r.str(3))))
    out.table("const SidekickFeature SIDEKICK_FEATURES[]", rows,
              "SIDEKICK_FEATURE_COUNT")

    progs = {}
    for r in tags.get("PROGRESSION", []):
        vals = [v.strip() for v in r.str(1).split(",")]
        if len(vals) != 21:
            r.die("%r has %d levels, expected 21" % (r.str(0), len(vals)))
        progs[r.str(0)] = vals
    for key, cname in (("sidekick spellcaster cantrips",
                        "SPELLCASTER_CANTRIPS"),
                       ("sidekick spellcaster spells known",
                        "SPELLCASTER_SPELLS_KNOWN")):
        if key not in progs:
            sys.exit("data/world.txt: no PROGRESSION named %r" % key)
        out.w("\nconst unsigned char %s[MAX_LEVEL + 1] = {\n    %s\n};\n"
              % (cname, ", ".join(progs[key])))

    # --- the background tables, each row carrying the rolls that produce it
    rows_by_table = {}
    for r in tags.get("LIFEROW", []):
        rows_by_table.setdefault(r.str(0), []).append(r)
    tables = tags.get("LIFETABLE", [])
    out.w("\n/* Xanathar's background tables. */\n")
    for n, t in enumerate(tables):
        name = t.str(0)
        if name not in rows_by_table:
            t.die("no LIFEROW lines belong to %r" % name)
        out.w("static const LifeEntry LIFEROWS_%d[] = {\n" % n)
        for r in rows_by_table[name]:
            if r.int(1) > r.int(2):
                r.die("%d-%d runs backwards" % (r.int(1), r.int(2)))
            out.w("    { %d, %d, %s },\n"
                  % (r.int(1), r.int(2), cstr(r.str(3))))
        out.w("};\n")
    named = set(t.str(0) for t in tables)
    for name, rs in rows_by_table.items():
        if name not in named:
            rs[0].die("no LIFETABLE named %r" % name)

    out.table(
        "const LifeTable LIFE_TABLES[]",
        ["    { %s, %s,\n      LIFEROWS_%d,"
         " (int)(sizeof(LIFEROWS_%d) / sizeof(LIFEROWS_%d[0])) }"
         % (cstr(t.str(0)), cstr(t.str(1)), n, n, n)
         for n, t in enumerate(tables)],
        "LIFE_TABLE_COUNT")

    out.save()


def sk_rows(tags):
    return tags.get("SIDEKICKCLASS", [])


# --------------------------------------------------------------------- main


def main():
    classes, subclasses = build_character()
    build_equipment()
    build_spells()
    build_world()
    print("%d classes, %d subclasses" % (len(classes), len(subclasses)))


if __name__ == "__main__":
    main()
