#!/usr/bin/env python3
"""Pull the subclass spell tables out of Xanathar's and Tasha's.

Domain, oath, circle, patron and specialist spell tables are printed beside
body text in two columns, so the OCR runs a table row and a sentence of prose
together on one line. Rather than trying to find where the row ends, each line
is matched against the spell database: the longest run of known spell names at
the start of the row is the row's content, and the prose that follows simply
fails to match.

The rows of a table are in ascending order, and how many spells each row holds
is fixed by the kind of subclass, so the extracted names are assigned to
levels by position. The count is printed for review.

Output is the '|' separated form that data_subclasses.c expects.
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import extract_spells as E                                   # noqa: E402

XGE = os.path.join(ROOT, "TextFiles", "XANATHARtext.txt")
TCE = os.path.join(ROOT, "TextFiles", "TASHAtext.txt")

# (book, heading line, subclass name, spells per row, number of rows)
TABLES = [
    (XGE, 2762, "Forge Domain", 2, 5),
    (XGE, 2990, "Grave Domain", 2, 5),
    (XGE, 5866, "Oath of Conquest", 2, 5),
    (XGE, 6071, "Oath of Redemption", 2, 5),
    (XGE, 6487, "Gloom Stalker", 1, 5),
    (XGE, 6606, "Horizon Walker", 1, 5),
    (XGE, 6736, "Monster Slayer", 1, 5),
    (XGE, 8529, "The Celestial", 2, 5),
    (XGE, 8655, "The Hexblade", 2, 5),
    (TCE, 1757, "Alchemist", 2, 5),
    (TCE, 1924, "Armorer", 2, 5),
    (TCE, 2152, "Artillerist", 2, 5),
    (TCE, 2359, "Battle Smith", 2, 5),
    (TCE, 3983, "Order Domain", 2, 5),
    (TCE, 4149, "Peace Domain", 2, 5),
    (TCE, 4311, "Twilight Domain", 2, 5),
    (TCE, 4574, "Circle of Spores", 2, 5),
    (TCE, 4960, "Circle of Wildfire", 2, 5),
    (TCE, 7231, "Fey Wanderer", 1, 5),
    (TCE, 7421, "Swarmkeeper", 1, 5),
    (TCE, 8306, "Aberrant Mind", 2, 5),
    (TCE, 8488, "Clockwork Soul", 2, 5),
    (TCE, 8973, "The Fathomless", 2, 5),
    (TCE, 9081, "The Genie", 2, 5),
]


def spell_index():
    """Every spell name in the generated database, keyed canonically."""
    src = open(os.path.join(ROOT, "src", "data_spells.c")).read()
    names = re.findall(r'^\s*\{ "((?:[^"\\]|\\.)*)",', src, re.M)
    return {E.canon(n): n for n in names}


def longest_spell_prefix(words, index):
    """Longest run of words from the start that names a spell."""
    for take in range(min(len(words), 6), 0, -1):
        key = E.canon(" ".join(words[:take]))
        if key in index:
            return index[key], take
    return None, 0


def parse_row(line, index, want):
    """Reads up to `want` spell names from the start of a table row."""
    body = line.strip()
    if not body:
        return []

    # Drop a leading level marker: the first token, when it is not itself
    # the start of a spell name ("1st", "Sth", "lai", "Cleric Level").
    words = body.replace(",", " , ").split()
    found = []
    while words and len(found) < want:
        if words[0] == ",":
            words.pop(0)
            continue
        name, used = longest_spell_prefix([w for w in words if w != ","], index)
        if name is None:
            # Skip one token and try again, but only before anything matched;
            # once a spell has been read, an unmatched token is prose.
            if found:
                break
            words.pop(0)
            continue
        found.append(name)
        # Consume the words the match used, ignoring the comma placeholders.
        consumed = 0
        while words and consumed < used:
            if words[0] != ",":
                consumed += 1
            words.pop(0)
    return found


def main():
    index = spell_index()
    print("/* Generated by tools/extract_subclass_spells.py -- review before use. */")
    problems = 0

    for path, line_no, name, per_row, rows in TABLES:
        lines = E.load_lines(path)
        want_total = per_row * rows
        collected = []

        for raw in lines[line_no: line_no + 60]:
            if len(collected) >= want_total:
                break
            got = parse_row(raw, index, per_row)
            if got:
                collected.append(got)

        flat = [s for row in collected for s in row]
        status = "ok" if len(flat) == want_total else "MISMATCH"
        if status != "ok":
            problems += 1

        print('\n/* %-22s %s: %d of %d spells */' %
              (name, status, len(flat), want_total))
        groups = []
        for row in collected[:rows]:
            groups.append(", ".join(s.lower() for s in row))
        print('  "%s"' % "|".join(groups))

    if problems:
        print("\n/* %d table(s) need checking by hand */" % problems)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
