/* data_life.c -- Xanathar's "This Is Your Life" tables.
 *
 * Generated by tools/extract_life.py; do not edit by hand.
 *
 * Each table can be rolled on or picked from, so the rows
 * carry their result range as well as their text.
 */
#include "data.h"

static const LifeEntry rows_0[] = {
{ 1, 50, "Home" },
{ 51, 55, "Home of a family friend" },
{ 56, 63, "Home of a healer or midwife" },
{ 64, 65, "Carriage, cart, or wagon" },
{ 66, 68, "Barn, shed, or other outbuilding" },
{ 69, 70, "Cave" },
{ 71, 72, "Field" },
{ 73, 74, "Forest" },
{ 75, 77, "Temple" },
{ 78, 78, "Battlefield" },
{ 79, 80, "Alley or street" },
{ 81, 82, "Brothel, tavern, or inn" },
{ 83, 84, "Castle, keep, tower, or palace" },
{ 85, 85, "Sewer or rubbish heap" },
{ 86, 88, "Among people of a different race" },
{ 89, 91, "On board a boat or a ship" },
{ 92, 93, "In a prison or in the headquarters of a secret organization" },
{ 94, 95, "In a sages laboratory" },
{ 96, 96, "In the Feywild" },
{ 97, 97, "In the Shadowfell" },
{ 98, 98, "On the Astral Plane or the Ethereal Plane" },
{ 99, 99, "On an Inner Plane of your choice" },
{ 100, 100, "On an Outer Plane of your choice" },
};

static const LifeEntry rows_1[] = {
{ 1, 2, "None" },
{ 3, 4, "1d3" },
{ 5, 6, "1d4+1" },
{ 7, 8, "1d6+2" },
{ 9, 10, "1d8 +3" },
};

static const LifeEntry rows_2[] = {
{ 2, 2, "Twin, triplet, or quadruplet" },
{ 3, 7, "Older" },
{ 8, 12, "Younger" },
};

static const LifeEntry rows_3[] = {
{ 1, 1, "None" },
{ 2, 2, "Institution, such as an asylum" },
{ 3, 3, "Temple" },
{ 4, 5, "Orphanage" },
{ 6, 7, "Guardian" },
{ 8, 15, "Paternal or maternal aunt, uncle, or both; or extended family such as a tribe or clan" },
{ 16, 25, "Paternal or maternal grandparent(s)" },
{ 26, 35, "Adoptive family (same or different race)" },
{ 36, 55, "Single father or stepfather" },
{ 56, 75, "Single mother or stepmother" },
{ 76, 100, "Mother and father" },
};

static const LifeEntry rows_4[] = {
{ 1, 1, "Your parent died (roll on the Cause of Death supplemental table)" },
{ 2, 2, "Your parent was imprisoned, enslaved, or otherwise taken away" },
{ 3, 3, "Your parent abandoned you" },
{ 4, 4, "Your parent disappeared to an unknown fate" },
};

static const LifeEntry rows_5[] = {
{ 3, 3, "Wretched (-40)" },
{ 4, 5, "Squalid (-20)" },
{ 6, 8, "Poor (-10)" },
{ 9, 12, "Modest (+0)" },
{ 13, 15, "Comfortable (+10)" },
{ 16, 17, "Wealthy (+20)" },
{ 18, 18, "Aristocratic (+40)" },
};

static const LifeEntry rows_6[] = {
{ 1, 20, "Rundown shack" },
{ 21, 30, "No permanent residence; you moved around a lot" },
{ 31, 40, "Encampment or village in the wilderness" },
{ 41, 50, "Apartment in a rundown neighborhood" },
{ 51, 70, "Small house" },
{ 71, 90, "Large house" },
{ 91, 110, "Mansion ll orhigher Palace or castle style table to arrive at the result" },
};

static const LifeEntry rows_7[] = {
{ 3, 3, "I amstill haunted by my childhood, when I was treated badly by my peers" },
{ 4, 5, "I spent most of my childhood alone, with no close friends" },
{ 6, 8, "Others saw me as being different or strange, and so I had few companions" },
{ 9, 12, "I had a few close friends and lived an ordinary childhood jah" },
{ 13, 15, "I had several friends, and my childhood was generally a happy one" },
{ 16, 17, "I always found it easy to make friends, and I loved being around people" },
{ 18, 18, "Everyone knew who I was, and I had friends everywhere I went" },
{ 64, 64, "NX CHAPTER 1 I'CHARACTER OPTIONS" },
};

static const LifeEntry rows_8[] = {
{ 1, 5, "Academic" },
{ 6, 10, "Adventurer (roll on the Class table) an Aristocrat" },
{ 11, 11, "Aristocrat" },
{ 12, 26, "Artisan or guild member" },
{ 27, 31, "Criminal" },
{ 32, 36, "Entertainer" },
{ 37, 38, "Exile, hermit, or refugee" },
{ 39, 43, "Explorer or wanderer" },
{ 44, 55, "Farmer or herder" },
{ 56, 60, "Hunter or trapper" },
{ 61, 75, "Laborer" },
{ 76, 80, "Merchant" },
{ 81, 85, "Politician or bureaucrat" },
{ 86, 90, "Priest" },
{ 91, 95, "Sailor" },
{ 96, 100, "Soldier es" },
};

static const LifeEntry rows_9[] = {
{ 3, 3, "Dead (roll on the Cause of Death table)" },
{ 4, 5, "Missing or unknown" },
{ 6, 8, "Alive, but doing poorly due to injury, financial trouble, or relationship difficulties" },
{ 9, 12, "Alive and well" },
{ 13, 15, "Alive and quite successful" },
{ 16, 17, "Alive and infamous" },
{ 18, 18, "Alive and famous collection of facts and notes that-at a minimum-encapsulate what your character has been doing in the world" },
};

static const LifeEntry rows_10[] = {
{ 3, 4, "Hostile" },
{ 5, 10, "Friendly" },
{ 11, 12, "Indifferent" },
};

const LifeTable LIFE_TABLES[] = {
{ "Birthplace", "d100", rows_0, 23 },
{ "Number of siblings", "d10", rows_1, 5 },
{ "Birth order", "2d6", rows_2, 3 },
{ "Who raised you", "d100", rows_3, 11 },
{ "The absent parent", "d4", rows_4, 4 },
{ "Family lifestyle", "3d6", rows_5, 7 },
{ "Childhood home", "3d6", rows_6, 7 },
{ "Childhood memories", "3d6", rows_7, 8 },
{ "Occupation", "d100", rows_8, 16 },
{ "Status", "3d6", rows_9, 7 },
{ "Relationship", "3d4", rows_10, 3 },
};
const int LIFE_TABLE_COUNT =
    (int)(sizeof(LIFE_TABLES) / sizeof(LIFE_TABLES[0]));
