/* data_deities.c -- the gods of Player's Handbook appendix B.
 *
 * A cleric or paladin chooses a deity, and the suggested domains are what
 * make that choice mean something mechanically, so each entry carries them
 * as text the domain menu can be read against.
 *
 * These are typed out rather than extracted: the text dump carries complete
 * columns for the Forgotten Realms table only, and the other seven
 * pantheons lost their alignment, domain and symbol columns entirely.
 */
#include "data.h"

#include <string.h>

const Deity DEITIES[] = {

/* ------------------------------------------------------ Forgotten Realms */
{ "Auril", "goddess of winter", "Forgotten Realms", "NE",
  "Nature, Tempest", "Six-pointed snowflake" },
{ "Azuth", "god of wizards", "Forgotten Realms", "LN",
  "Knowledge", "Left hand pointing upward, outlined in fire" },
{ "Bane", "god of tyranny", "Forgotten Realms", "LE",
  "War", "Upright black right hand, thumb and fingers together" },
{ "Beshaba", "goddess of misfortune", "Forgotten Realms", "CE",
  "Trickery", "Black antlers" },
{ "Bhaal", "god of murder", "Forgotten Realms", "NE",
  "Death", "Skull surrounded by a ring of blood droplets" },
{ "Chauntea", "goddess of agriculture", "Forgotten Realms", "NG",
  "Life", "Sheaf of grain or a blooming rose over grain" },
{ "Cyric", "god of lies", "Forgotten Realms", "CE",
  "Trickery", "White jawless skull on black or purple sunburst" },
{ "Deneir", "god of writing", "Forgotten Realms", "NG",
  "Knowledge", "Lit candle above an open eye" },
{ "Eldath", "goddess of peace", "Forgotten Realms", "NG",
  "Life, Nature", "Waterfall plunging into a still pool" },
{ "Gond", "god of craft", "Forgotten Realms", "N",
  "Knowledge", "Toothed cog with four spokes" },
{ "Helm", "god of protection", "Forgotten Realms", "LN",
  "Life, Light", "Staring eye on upright left gauntlet" },
{ "Ilmater", "god of endurance", "Forgotten Realms", "LG",
  "Life", "Hands bound at the wrist with red cord" },
{ "Kelemvor", "god of the dead", "Forgotten Realms", "LN",
  "Death", "Upright skeletal arm holding balanced scales" },
{ "Lathander", "god of birth and renewal", "Forgotten Realms", "NG",
  "Life, Light", "Road travelling into a sunrise" },
{ "Leira", "goddess of illusion", "Forgotten Realms", "CN",
  "Trickery", "Point-down triangle containing a swirl of mist" },
{ "Lliira", "goddess of joy", "Forgotten Realms", "CG",
  "Life", "Triangle of three six-pointed stars" },
{ "Loviatar", "goddess of pain", "Forgotten Realms", "LE",
  "Death", "Nine-tailed barbed scourge" },
{ "Malar", "god of the hunt", "Forgotten Realms", "CE",
  "Nature", "Clawed paw" },
{ "Mask", "god of thieves", "Forgotten Realms", "CN",
  "Trickery", "Black mask" },
{ "Mielikki", "goddess of forests", "Forgotten Realms", "NG",
  "Nature", "Unicorn's head" },
{ "Milil", "god of poetry and song", "Forgotten Realms", "NG",
  "Light", "Five-stringed harp made of leaves" },
{ "Myrkul", "god of death", "Forgotten Realms", "NE",
  "Death", "White human skull" },
{ "Mystra", "goddess of magic", "Forgotten Realms", "NG",
  "Knowledge", "Circle of seven stars, or nine stars encircling a "
  "flowing red mist, or a single star" },
{ "Oghma", "god of knowledge", "Forgotten Realms", "N",
  "Knowledge", "Blank scroll" },
{ "Savras", "god of divination and fate", "Forgotten Realms", "LN",
  "Knowledge", "Crystal ball containing many kinds of eyes" },
{ "Selune", "goddess of the moon", "Forgotten Realms", "CG",
  "Knowledge, Life", "Pair of eyes surrounded by seven stars" },
{ "Shar", "goddess of darkness and loss", "Forgotten Realms", "NE",
  "Death, Trickery", "Black disk encircled with a purple border" },
{ "Silvanus", "god of wild nature", "Forgotten Realms", "N",
  "Nature", "Oak leaf" },
{ "Sune", "goddess of love and beauty", "Forgotten Realms", "CG",
  "Life, Light", "Face of a beautiful red-haired woman" },
{ "Talona", "goddess of disease and poison", "Forgotten Realms", "CE",
  "Death", "Three teardrops on a triangle" },
{ "Talos", "god of storms", "Forgotten Realms", "CE",
  "Tempest", "Three lightning bolts radiating from a point" },
{ "Tempus", "god of war", "Forgotten Realms", "N",
  "War", "Upright flaming sword" },
{ "Torm", "god of courage and self-sacrifice", "Forgotten Realms", "LG",
  "War", "White right gauntlet" },
{ "Tymora", "goddess of good fortune", "Forgotten Realms", "CG",
  "Trickery", "Face-up coin" },
{ "Tyr", "god of justice", "Forgotten Realms", "LG",
  "War", "Balanced scales resting on a warhammer" },
{ "Umberlee", "goddess of the sea", "Forgotten Realms", "CE",
  "Tempest", "Wave curling left and right" },
{ "Waukeen", "goddess of trade", "Forgotten Realms", "N",
  "Knowledge, Trickery", "Upright coin with Waukeen's profile facing left" },

/* -------------------------------------------------------------- Greyhawk */
{ "Beory", "goddess of nature", "Greyhawk", "N",
  "Nature", "Green disk" },
{ "Boccob", "god of magic", "Greyhawk", "N",
  "Knowledge", "Eye within a pentagram" },
{ "Celestian", "god of stars and wanderers", "Greyhawk", "N",
  "Knowledge", "Arc of seven stars inside a circle" },
{ "Ehlonna", "goddess of woodlands", "Greyhawk", "NG",
  "Life, Nature", "Unicorn horn" },
{ "Erythnul", "god of envy and slaughter", "Greyhawk", "CE",
  "War", "Blood drop" },
{ "Fharlanghn", "god of horizons and travel", "Greyhawk", "NG",
  "Knowledge, Trickery", "Circle crossed by a curved horizon line" },
{ "Heironeous", "god of chivalry and valour", "Greyhawk", "LG",
  "War", "Hand holding a lightning bolt" },
{ "Hextor", "god of war and discord", "Greyhawk", "LE",
  "War", "Six arrows facing downward in a fan" },
{ "Kord", "god of athletics and sport", "Greyhawk", "CG",
  "Tempest, War", "Four spears and four maces radiating from a point" },
{ "Incabulos", "god of plague and famine", "Greyhawk", "NE",
  "Death", "Green triangle with a black border" },
{ "Istus", "goddess of fate and destiny", "Greyhawk", "N",
  "Knowledge", "Weaving spindle" },
{ "Iuz", "god of pain and oppression", "Greyhawk", "CE",
  "Death, Trickery", "Grinning human skull" },
{ "Nerull", "god of death", "Greyhawk", "NE",
  "Death", "Skull and scythe" },
{ "Obad-Hai", "god of nature", "Greyhawk", "N",
  "Nature", "Oak leaf and acorn" },
{ "Olidammara", "god of revelry", "Greyhawk", "CN",
  "Trickery", "Laughing mask" },
{ "Pelor", "god of the sun and healing", "Greyhawk", "NG",
  "Life, Light", "Sun" },
{ "Pholtus", "god of light and law", "Greyhawk", "LG",
  "Light", "Silver sun partially eclipsed by a crescent moon" },
{ "Ralishaz", "god of ill luck and insanity", "Greyhawk", "CN",
  "Trickery", "Three bone fate-casting sticks" },
{ "Rao", "god of peace and reason", "Greyhawk", "LG",
  "Knowledge", "White heart" },
{ "St. Cuthbert", "god of common sense and zeal", "Greyhawk", "LN",
  "Knowledge", "Circle at the centre of a starburst of lines" },
{ "Tharizdun", "god of eternal darkness", "Greyhawk", "CE",
  "Trickery", "Dark spiral or inverted ziggurat" },
{ "Trithereon", "god of liberty and retribution", "Greyhawk", "CG",
  "War", "Triskelion" },
{ "Ulaa", "goddess of hills and mountains", "Greyhawk", "LG",
  "Life, War", "Mountain with a circle at its heart" },
{ "Vecna", "god of evil secrets", "Greyhawk", "NE",
  "Knowledge", "Partly shattered one-eyed skull" },
{ "Wee Jas", "goddess of magic and death", "Greyhawk", "LN",
  "Death, Knowledge", "Red skull in front of a fireball" },

/* ----------------------------------------------------------- Dragonlance */
{ "Paladine", "god of rulers and guardians", "Dragonlance", "LG",
  "War", "Silver triangle" },
{ "Branchala", "god of music", "Dragonlance", "NG",
  "Light", "Bard's harp" },
{ "Habbakuk", "god of animal life and the sea", "Dragonlance", "NG",
  "Nature, Tempest", "Blue bird" },
{ "Kiri-Jolith", "god of honour and war", "Dragonlance", "LG",
  "War", "Bison's horns" },
{ "Majere", "god of meditation and order", "Dragonlance", "LG",
  "Knowledge", "Copper spider" },
{ "Mishakal", "goddess of healing", "Dragonlance", "LG",
  "Knowledge, Life", "Blue infinity sign" },
{ "Solinari", "god of good magic", "Dragonlance", "LG",
  "None", "White circle or sphere" },
{ "Gilean", "god of knowledge", "Dragonlance", "N",
  "Knowledge", "Open book" },
{ "Chislev", "goddess of nature", "Dragonlance", "N",
  "Nature", "Feather" },
{ "Reorx", "god of craft", "Dragonlance", "N",
  "Knowledge", "Forging hammer" },
{ "Shinare", "goddess of wealth and trade", "Dragonlance", "N",
  "Knowledge, Trickery", "Griffon's wing" },
{ "Sirrion", "god of fire and change", "Dragonlance", "N",
  "Nature", "Multi-coloured fire" },
{ "Zivilyn", "god of wisdom", "Dragonlance", "N",
  "Knowledge", "Great green or gold tree" },
{ "Lunitari", "goddess of neutral magic", "Dragonlance", "N",
  "None", "Red circle or sphere" },
{ "Takhisis", "goddess of night and hatred", "Dragonlance", "LE",
  "Death", "Black crescent" },
{ "Chemosh", "god of the undead", "Dragonlance", "LE",
  "Death", "Yellow skull" },
{ "Hiddukel", "god of lies and greed", "Dragonlance", "CE",
  "Trickery", "Broken merchant's scales" },
{ "Morgion", "god of disease and secrecy", "Dragonlance", "NE",
  "Death", "Hood with two red eyes" },
{ "Sargonnas", "god of vengeance and fire", "Dragonlance", "LE",
  "War", "Stylised red condor" },
{ "Zeboim", "goddess of the sea and storms", "Dragonlance", "CE",
  "Tempest", "Turtle shell" },
{ "Nuitari", "god of evil magic", "Dragonlance", "LE",
  "None", "Black circle or sphere" },

/* --------------------------------------------------------------- Eberron */
{ "Arawai", "goddess of fertility", "Eberron", "NG",
  "Life, Nature", "Sheaf of wheat tied with green ribbon" },
{ "Aureon", "god of law and knowledge", "Eberron", "LN",
  "Knowledge", "Open tome" },
{ "Balinor", "god of beasts and the hunt", "Eberron", "N",
  "Life, Nature", "Pair of antlers" },
{ "Boldrei", "goddess of community and home", "Eberron", "LG",
  "Life", "Fire in a stone hearth" },
{ "Dol Arrah", "goddess of sunlight and honour", "Eberron", "LG",
  "Light, War", "Rising sun" },
{ "Dol Dorn", "god of strength at arms", "Eberron", "CG",
  "War", "Longsword crossed over a shield" },
{ "Kol Korran", "god of trade and wealth", "Eberron", "N",
  "Trickery", "Nine-sided gold coin" },
{ "Olladra", "goddess of good fortune", "Eberron", "NG",
  "Life, Trickery", "Domino" },
{ "Onatar", "god of craft", "Eberron", "NG",
  "Knowledge", "Crossed hammer and tongs" },
{ "The Devourer", "god of nature's wrath", "Eberron", "NE",
  "Tempest", "Bundle of five sharpened bones" },
{ "The Fury", "goddess of passion", "Eberron", "NE",
  "War", "Winged serpent with a woman's head" },
{ "The Keeper", "god of greed and death", "Eberron", "NE",
  "Death", "Dragonshard stone in the shape of a fang" },
{ "The Mockery", "god of violence and treachery", "Eberron", "NE",
  "War", "Five bloody tools" },
{ "The Shadow", "god of dark magic", "Eberron", "CE",
  "Knowledge", "Obsidian tower" },
{ "The Traveller", "deity of chaos and change", "Eberron", "CN",
  "Knowledge, Trickery", "Four crossed, forking paths" },
{ "The Blood of Vol", "belief in divinity of blood and undeath",
  "Eberron", "LE", "Death, Life", "Stylised red teardrop" },
{ "The Silver Flame", "devotion to good", "Eberron", "LG",
  "Life, Light, War", "Flame drawn on silver or contained in silver" },
{ "The Undying Court", "elven ancestors", "Eberron", "NG",
  "Knowledge, Life", "Varies by ancestor" },

/* ---------------------------------------------------------------- Celtic */
{ "The Daghdha", "god of weather and crops", "Celtic", "CG",
  "Nature, Trickery", "Bubbling cauldron or shield" },
{ "Arawn", "god of life and death", "Celtic", "NE",
  "Life, Death", "Black star on grey background" },
{ "Belenus", "god of sun, light and warmth", "Celtic", "NG",
  "Light", "Solar disk and standing stones" },
{ "Brigantia", "goddess of rivers and livestock", "Celtic", "NG",
  "Life", "Footbridge" },
{ "Diancecht", "god of medicine and healing", "Celtic", "LG",
  "Life", "Crossed oak and mistletoe branches" },
{ "Dunatis", "god of mountains and peaks", "Celtic", "N",
  "Nature", "Red sun-capped mountain peak" },
{ "Goibhniu", "god of smiths and healing", "Celtic", "NG",
  "Knowledge, Life", "Giant mallet over sword" },
{ "Lugh", "god of arts, travel and commerce", "Celtic", "CN",
  "Knowledge, Life", "Pair of long hands" },
{ "Manannan mac Lir", "god of oceans and sea creatures", "Celtic", "LN",
  "Nature, Tempest", "Wave of white water on green" },
{ "Math Mathonwy", "god of magic", "Celtic", "NE",
  "Knowledge", "Staff" },
{ "Morrigan", "goddess of battle", "Celtic", "CE",
  "War", "Two crossed spears" },
{ "Nuada", "god of war and warriors", "Celtic", "N",
  "War", "Silver hand on black background" },
{ "Oghma", "god of speech and writing", "Celtic", "NG",
  "Knowledge", "Unfurled scroll" },
{ "Silvanus", "god of nature and forests", "Celtic", "N",
  "Nature", "Summer oak tree" },

/* ----------------------------------------------------------------- Greek */
{ "Zeus", "god of the sky, ruler of the gods", "Greek", "N",
  "Tempest", "Fist full of lightning bolts" },
{ "Aphrodite", "goddess of love and beauty", "Greek", "CG",
  "Light", "Sea shell" },
{ "Apollo", "god of light, music and healing", "Greek", "CG",
  "Knowledge, Life, Light", "Lyre" },
{ "Ares", "god of war and strife", "Greek", "CE",
  "War", "Spear" },
{ "Artemis", "goddess of hunting and childbirth", "Greek", "NG",
  "Life, Nature", "Bow and arrow on lunar disk" },
{ "Athena", "goddess of wisdom and civilization", "Greek", "LG",
  "Knowledge, War", "Owl" },
{ "Demeter", "goddess of agriculture", "Greek", "NG",
  "Life", "Mare's head" },
{ "Dionysus", "god of mirth and wine", "Greek", "CN",
  "Life", "Thyrsus (staff tipped with pine cone)" },
{ "Hades", "god of the underworld", "Greek", "LE",
  "Death", "Black ram" },
{ "Hecate", "goddess of magic and the moon", "Greek", "CE",
  "Knowledge, Trickery", "Setting moon" },
{ "Hephaestus", "god of smithing and craft", "Greek", "NG",
  "Knowledge", "Hammer and anvil" },
{ "Hera", "goddess of marriage and intrigue", "Greek", "CN",
  "Trickery", "Fan of peacock feathers" },
{ "Hercules", "god of strength and adventure", "Greek", "CG",
  "Tempest, War", "Lion's head" },
{ "Hermes", "god of travel and commerce", "Greek", "CG",
  "Trickery", "Caduceus (winged staff and serpents)" },
{ "Hestia", "goddess of home and family", "Greek", "NG",
  "Life", "Hearth" },
{ "Nike", "goddess of victory", "Greek", "LN",
  "War", "Winged woman" },
{ "Pan", "god of nature and the wild", "Greek", "CN",
  "Nature", "Syrinx (pan pipes)" },
{ "Poseidon", "god of the sea and earthquakes", "Greek", "CN",
  "Tempest", "Trident" },
{ "Tyche", "goddess of good fortune", "Greek", "N",
  "Trickery", "Red pentagram" },

/* -------------------------------------------------------------- Egyptian */
{ "Re-Horakhty", "god of the sun, ruler of the gods", "Egyptian", "LG",
  "Life, Light", "Solar disk encircled by serpent" },
{ "Anubis", "god of judgment and death", "Egyptian", "LN",
  "Death", "Black jackal" },
{ "Apep", "god of evil, fire and serpents", "Egyptian", "NE",
  "Trickery", "Flaming snake" },
{ "Bast", "goddess of cats and vengeance", "Egyptian", "CG",
  "War", "Cat" },
{ "Bes", "god of luck and music", "Egyptian", "CN",
  "Trickery", "Image of the misshapen dwarf himself" },
{ "Hathor", "goddess of love, music and motherhood", "Egyptian", "NG",
  "Life, Light", "Horned cow's head with lunar disk" },
{ "Imhotep", "god of craft and medicine", "Egyptian", "NG",
  "Knowledge", "Step pyramid" },
{ "Isis", "goddess of fertility and magic", "Egyptian", "NG",
  "Knowledge, Life", "Ankh and star" },
{ "Nephthys", "goddess of death and grief", "Egyptian", "CG",
  "Death", "Horns around a lunar disk" },
{ "Osiris", "god of nature and the underworld", "Egyptian", "LG",
  "Life, Nature", "Crook and flail" },
{ "Ptah", "god of crafts, knowledge and secrets", "Egyptian", "LN",
  "Knowledge", "Bull" },
{ "Set", "god of darkness and desert storms", "Egyptian", "CE",
  "Death, Tempest, Trickery", "Coiled cobra" },
{ "Sobek", "god of water and crocodiles", "Egyptian", "LE",
  "Nature, Tempest", "Crocodile head with horns and plumes" },
{ "Thoth", "god of knowledge and wisdom", "Egyptian", "N",
  "Knowledge", "Ibis" },

/* ----------------------------------------------------------------- Norse */
{ "Odin", "god of knowledge and war", "Norse", "NG",
  "Knowledge, War", "Watching blue eye" },
{ "Aegir", "god of the sea and storms", "Norse", "NE",
  "Tempest", "Rough ocean waves" },
{ "Balder", "god of beauty and poetry", "Norse", "NG",
  "Life, Light", "Gem-encrusted silver chalice" },
{ "Forseti", "god of justice and law", "Norse", "N",
  "Light", "Head of a bearded man" },
{ "Frey", "god of fertility and the sun", "Norse", "NG",
  "Life, Light", "Ice-blue greatsword" },
{ "Freya", "goddess of fertility and love", "Norse", "NG",
  "Life", "Cat" },
{ "Frigga", "goddess of birth and fertility", "Norse", "N",
  "Life, Light", "Cat" },
{ "Heimdall", "god of watchfulness and loyalty", "Norse", "LG",
  "Light, War", "Curling musical horn" },
{ "Hel", "goddess of the underworld", "Norse", "NE",
  "Death", "Woman's face, rotting on one side" },
{ "Hermod", "god of luck", "Norse", "CN",
  "Trickery", "Winged scroll" },
{ "Loki", "god of thieves and trickery", "Norse", "CE",
  "Trickery", "Flame" },
{ "Njord", "god of sea and wind", "Norse", "NG",
  "Nature, Tempest", "Gold coin" },
{ "Odur", "god of light and the sun", "Norse", "CG",
  "Light", "Solar disk" },
{ "Sif", "goddess of war", "Norse", "CG",
  "War", "Upraised sword" },
{ "Skadi", "god of earth and mountains", "Norse", "N",
  "Nature", "Mountain peak" },
{ "Surtur", "god of fire giants and war", "Norse", "LE",
  "War", "Flaming sword" },
{ "Thrym", "god of frost giants and cold", "Norse", "CE",
  "War", "White double-bladed axe" },
{ "Thor", "god of storms and thunder", "Norse", "CG",
  "Tempest, War", "Hammer" },
{ "Tyr", "god of courage and strategy", "Norse", "LN",
  "Knowledge, War", "Sword" },
{ "Uller", "god of hunting and winter", "Norse", "CN",
  "Nature", "Longbow" },

/* ---------------------------------------- nonhuman deities of the Realms */
{ "Corellon Larethian", "elf deity of art and magic", "Nonhuman", "CG",
  "Light", "Quarter moon or starburst" },
{ "Moradin", "dwarf deity of creation", "Nonhuman", "LG",
  "Knowledge", "Hammer and anvil" },
{ "Garl Glittergold", "gnome deity of trickery and wiles", "Nonhuman", "LG",
  "Trickery", "Gold nugget" },
{ "Yondalla", "halfling deity of fertility and protection", "Nonhuman", "LG",
  "Life", "Cornucopia on a shield" },
{ "Gruumsh", "orc deity of storms and war", "Nonhuman", "CE",
  "Tempest, War", "Unblinking eye" },
{ "Bahamut", "dragon deity of good dragonkind", "Nonhuman", "LG",
  "Life, War", "Dragon's head in profile" },
{ "Tiamat", "dragon deity of evil dragonkind", "Nonhuman", "LE",
  "Trickery", "Dragon head with five claw marks" },
{ "Lolth", "drow deity of spiders", "Nonhuman", "CE",
  "Trickery", "Spider" },
{ "Sehanine Moonbow", "elf deity of the moon", "Nonhuman", "CG",
  "Knowledge", "Crescent moon" },
{ "Sekolah", "sahuagin deity of the hunt", "Nonhuman", "LE",
  "Nature, Tempest", "Shark" },
{ "Semuanya", "lizardfolk deity of survival", "Nonhuman", "N",
  "Life", "Egg" },
{ "Skerrit", "centaur and satyr deity of nature", "Nonhuman", "N",
  "Nature", "Oak growing from acorn" },
{ "Surtur", "giant deity of craft and fire", "Nonhuman", "LE",
  "Knowledge, War", "Flaming sword" },
{ "Thryn", "giant deity of frost and strength", "Nonhuman", "CE",
  "War", "White double-bladed axe" },
{ "Grolantor", "hill giant deity of war", "Nonhuman", "CE",
  "War", "Wooden club" },
{ "Hruggek", "bugbear deity of violence", "Nonhuman", "CE",
  "War", "Morningstar" },
{ "Maglubiyet", "goblinoid deity of war", "Nonhuman", "LE",
  "War", "Bloody axe" },
{ "Kurtulmak", "kobold deity of war and mining", "Nonhuman", "LE",
  "War", "Gnome skull" },

};
const int DEITY_COUNT = (int)(sizeof(DEITIES) / sizeof(DEITIES[0]));

int find_deity(const char *name)
{
    int i;
    for (i = 0; i < DEITY_COUNT; i++)
        if (strcmp(DEITIES[i].name, name) == 0) return i;
    return -1;
}
