/* data_features.c -- class and subclass features by level (PHB chapter 3).
 *
 * Summaries are brief mechanical notes written for this program, not the
 * sourcebook's own wording.
 */
#include "data.h"

/* Class ids: 0 barbarian, 1 bard, 2 cleric, 3 druid, 4 fighter, 5 monk,
 * 6 paladin, 7 ranger, 8 rogue, 9 sorcerer, 10 warlock, 11 wizard.
 * Subclass ids index SUBCLASSES; -1 marks a base class feature. */

#define ASI_TEXT "Increase one ability score by 2, or two scores by 1 " \
                 "(maximum 20), or take a feat instead."

const FeatureData FEATURES[] = {
/* ============================ barbarian (0) ============================= */
{0,-1, 1,"Rage","Enter a rage as a bonus action: advantage on Strength checks and saves, bonus melee damage, resistance to bludgeoning, piercing and slashing damage."},
{0,-1, 1,"Unarmored Defense","With no armor, your AC equals 10 + Dexterity modifier + Constitution modifier. A shield still applies."},
{0,-1, 2,"Reckless Attack","Gain advantage on Strength-based melee attacks this turn; attacks against you have advantage until your next turn."},
{0,-1, 2,"Danger Sense","Advantage on Dexterity saving throws against effects you can see."},
{0,-1, 4,"Ability Score Improvement",ASI_TEXT},
{0,-1, 5,"Extra Attack","Attack twice when you take the Attack action."},
{0,-1, 5,"Fast Movement","Your speed increases by 10 feet while not wearing heavy armor."},
{0,-1, 7,"Feral Instinct","Advantage on initiative; you may act while surprised if you rage first."},
{0,-1, 8,"Ability Score Improvement",ASI_TEXT},
{0,-1, 9,"Brutal Critical","Roll one additional weapon damage die on a melee critical hit."},
{0,-1,11,"Relentless Rage","When reduced to 0 hit points while raging, make a DC 10 Constitution save to drop to 1 instead. The DC rises by 5 each use."},
{0,-1,12,"Ability Score Improvement",ASI_TEXT},
{0,-1,13,"Brutal Critical","Two additional weapon damage dice on a melee critical hit."},
{0,-1,15,"Persistent Rage","Your rage ends early only if you fall unconscious or choose to end it."},
{0,-1,16,"Ability Score Improvement",ASI_TEXT},
{0,-1,17,"Brutal Critical","Three additional weapon damage dice on a melee critical hit."},
{0,-1,18,"Indomitable Might","If your Strength check total is lower than your Strength score, use the score instead."},
{0,-1,19,"Ability Score Improvement",ASI_TEXT},
{0,-1,20,"Primal Champion","Strength and Constitution increase by 4; their maximum becomes 24."},
{0, 0, 3,"Frenzy","While raging you may frenzy, making a bonus-action melee attack each turn; you gain one level of exhaustion when the rage ends."},
{0, 0, 6,"Mindless Rage","You cannot be charmed or frightened while raging."},
{0, 0,10,"Intimidating Presence","Frighten a creature within 30 feet with a Wisdom save against your Charisma DC."},
{0, 0,14,"Retaliation","When a creature within 5 feet damages you, spend your reaction to make a melee attack against it."},
{0, 1, 3,"Spirit Seeker","You can cast beast sense and speak with animals as rituals."},
{0, 1, 3,"Totem Spirit","Bear: resistance to all damage but psychic while raging. Eagle: Dash as a bonus action. Wolf: allies have advantage on melee attacks against foes within 5 feet of you."},
{0, 1, 6,"Aspect of the Beast","Bear: doubled carrying capacity. Eagle: see 1 mile clearly, no disadvantage on dim-light Perception. Wolf: track at a fast pace and move stealthily at a normal pace."},
{0, 1,10,"Spirit Walker","You can cast commune with nature as a ritual."},
{0, 1,14,"Totemic Attunement","Bear: enemies within 5 feet have disadvantage attacking others. Eagle: fly while raging. Wolf: knock a Large or smaller creature prone on a melee hit."},

/* =============================== bard (1) =============================== */
{1,-1, 1,"Spellcasting","You cast bard spells using Charisma. Spell save DC 8 + proficiency + Charisma; attack bonus proficiency + Charisma."},
{1,-1, 1,"Bardic Inspiration (d6)","As a bonus action, give a creature a d6 to add to one ability check, attack roll or saving throw. Uses equal your Charisma modifier per long rest."},
{1,-1, 2,"Jack of All Trades","Add half your proficiency bonus, rounded down, to ability checks you are not proficient in."},
{1,-1, 2,"Song of Rest (d6)","Allies who spend Hit Dice at a short rest regain an extra d6 hit points."},
{1,-1, 3,"Expertise","Double your proficiency bonus for two skills you are proficient in."},
{1,-1, 4,"Ability Score Improvement",ASI_TEXT},
{1,-1, 5,"Bardic Inspiration (d8)","Your inspiration die becomes a d8."},
{1,-1, 5,"Font of Inspiration","You regain Bardic Inspiration uses on a short rest as well as a long rest."},
{1,-1, 6,"Countercharm","As an action, give allies within 30 feet advantage on saves against being frightened or charmed."},
{1,-1, 8,"Ability Score Improvement",ASI_TEXT},
{1,-1, 9,"Song of Rest (d8)","Your Song of Rest die becomes a d8."},
{1,-1,10,"Bardic Inspiration (d10)","Your inspiration die becomes a d10."},
{1,-1,10,"Expertise","Double your proficiency bonus for two more skills."},
{1,-1,10,"Magical Secrets","Learn two spells from any class's list; they count as bard spells."},
{1,-1,12,"Ability Score Improvement",ASI_TEXT},
{1,-1,13,"Song of Rest (d10)","Your Song of Rest die becomes a d10."},
{1,-1,14,"Magical Secrets","Learn two more spells from any class's list."},
{1,-1,15,"Bardic Inspiration (d12)","Your inspiration die becomes a d12."},
{1,-1,16,"Ability Score Improvement",ASI_TEXT},
{1,-1,17,"Song of Rest (d12)","Your Song of Rest die becomes a d12."},
{1,-1,18,"Magical Secrets","Learn two more spells from any class's list."},
{1,-1,19,"Ability Score Improvement",ASI_TEXT},
{1,-1,20,"Superior Inspiration","Regain one Bardic Inspiration use when you roll initiative with none left."},
{1, 2, 3,"Bonus Proficiencies","Gain proficiency in three skills of your choice."},
{1, 2, 3,"Cutting Words","Spend Bardic Inspiration as a reaction to subtract the die from a foe's attack, ability check or damage roll."},
{1, 2, 6,"Additional Magical Secrets","Learn two spells from any class's list; they do not count against spells known."},
{1, 2,14,"Peerless Skill","Spend Bardic Inspiration to add the die to your own ability check."},
{1, 3, 3,"Bonus Proficiencies","Gain proficiency with medium armor, shields and martial weapons."},
{1, 3, 3,"Combat Inspiration","A creature can add its inspiration die to a damage roll, or to its AC against one attack."},
{1, 3, 6,"Extra Attack","Attack twice when you take the Attack action."},
{1, 3,14,"Battle Magic","After casting a bard spell you may make one weapon attack as a bonus action."},

/* ============================== cleric (2) ============================== */
{2,-1, 1,"Spellcasting","You cast cleric spells using Wisdom, preparing Wisdom modifier + cleric level spells each long rest."},
{2,-1, 1,"Divine Domain","Choose a domain; it grants domain spells and features."},
{2,-1, 2,"Channel Divinity (1/rest)","Channel divine energy for a domain effect or to Turn Undead."},
{2,-1, 2,"Turn Undead","Undead within 30 feet that fail a Wisdom save are turned for 1 minute."},
{2,-1, 4,"Ability Score Improvement",ASI_TEXT},
{2,-1, 5,"Destroy Undead (CR 1/2)","Turned undead of CR 1/2 or lower are destroyed instead."},
{2,-1, 6,"Channel Divinity (2/rest)","You may use Channel Divinity twice between rests."},
{2,-1, 8,"Ability Score Improvement",ASI_TEXT},
{2,-1, 8,"Destroy Undead (CR 1)","Turned undead of CR 1 or lower are destroyed."},
{2,-1,10,"Divine Intervention","Call on your deity for aid; succeeds on a percentile roll under your cleric level."},
{2,-1,11,"Destroy Undead (CR 2)","Turned undead of CR 2 or lower are destroyed."},
{2,-1,12,"Ability Score Improvement",ASI_TEXT},
{2,-1,14,"Destroy Undead (CR 3)","Turned undead of CR 3 or lower are destroyed."},
{2,-1,16,"Ability Score Improvement",ASI_TEXT},
{2,-1,17,"Destroy Undead (CR 4)","Turned undead of CR 4 or lower are destroyed."},
{2,-1,18,"Channel Divinity (3/rest)","You may use Channel Divinity three times between rests."},
{2,-1,19,"Ability Score Improvement",ASI_TEXT},
{2,-1,20,"Divine Intervention Improvement","Your Divine Intervention automatically succeeds."},
{2, 4, 1,"Blessings of Knowledge","Learn two languages and gain expertise in two of Arcana, History, Nature or Religion."},
{2, 4, 2,"Channel Divinity: Knowledge of the Ages","Gain proficiency with one skill or tool for 10 minutes."},
{2, 4, 6,"Channel Divinity: Read Thoughts","Read a creature's thoughts and optionally cast suggestion on it."},
{2, 4, 8,"Potent Spellcasting","Add your Wisdom modifier to cleric cantrip damage."},
{2, 4,17,"Visions of the Past","Meditate to receive visions of an object's or place's past."},
{2, 5, 1,"Bonus Proficiency","Gain proficiency with heavy armor."},
{2, 5, 1,"Disciple of Life","Healing spells of 1st level or higher restore an extra 2 + the spell's level."},
{2, 5, 2,"Channel Divinity: Preserve Life","Restore hit points equal to five times your cleric level, split among creatures within 30 feet."},
{2, 5, 6,"Blessed Healer","Healing another creature also heals you for 2 + the spell's level."},
{2, 5, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 radiant damage, rising to 2d8 at 14th level."},
{2, 5,17,"Supreme Healing","Healing dice you would roll are treated as rolling their maximum."},
{2, 6, 1,"Bonus Cantrip","You know the light cantrip."},
{2, 6, 1,"Warding Flare","Impose disadvantage on an attack against you as a reaction, Wisdom modifier times per long rest."},
{2, 6, 2,"Channel Divinity: Radiance of the Dawn","Dispel magical darkness and deal 2d10 + cleric level radiant damage in a 30-foot radius."},
{2, 6, 6,"Improved Flare","You can use Warding Flare to protect another creature."},
{2, 6, 8,"Potent Spellcasting","Add your Wisdom modifier to cleric cantrip damage."},
{2, 6,17,"Corona of Light","Emit bright light for 1 minute; foes have disadvantage on saves against fire and radiant spells."},
{2, 7, 1,"Acolyte of Nature","Learn one druid cantrip and gain one skill from Animal Handling, Nature or Survival."},
{2, 7, 1,"Bonus Proficiency","Gain proficiency with heavy armor."},
{2, 7, 2,"Channel Divinity: Charm Animals and Plants","Charm beasts and plants within 30 feet that fail a Wisdom save."},
{2, 7, 6,"Dampen Elements","As a reaction, grant resistance to acid, cold, fire, lightning or thunder damage."},
{2, 7, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 cold, fire or lightning damage, rising to 2d8 at 14th level."},
{2, 7,17,"Master of Nature","Command charmed beasts and plants as a bonus action."},
{2, 8, 1,"Bonus Proficiencies","Gain proficiency with martial weapons and heavy armor."},
{2, 8, 1,"Wrath of the Storm","Deal 2d8 lightning or thunder damage as a reaction when hit in melee, Wisdom modifier times per long rest."},
{2, 8, 2,"Channel Divinity: Destructive Wrath","Deal maximum lightning or thunder damage instead of rolling."},
{2, 8, 6,"Thunderbolt Strike","Lightning damage you deal pushes a Large or smaller creature 10 feet."},
{2, 8, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 thunder damage, rising to 2d8 at 14th level."},
{2, 8,17,"Stormborn","You gain a flying speed equal to your walking speed outdoors."},
{2, 9, 1,"Blessing of the Trickster","Grant a creature advantage on Stealth checks for 1 hour."},
{2, 9, 2,"Channel Divinity: Invoke Duplicity","Create an illusory duplicate for 1 minute; gain advantage when both flank a target."},
{2, 9, 6,"Channel Divinity: Cloak of Shadows","Become invisible until the end of your next turn."},
{2, 9, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 poison damage, rising to 2d8 at 14th level."},
{2, 9,17,"Improved Duplicity","Invoke Duplicity creates up to four illusory duplicates."},
{2,10, 1,"Bonus Proficiencies","Gain proficiency with martial weapons and heavy armor."},
{2,10, 1,"War Priest","Make a weapon attack as a bonus action, Wisdom modifier times per long rest."},
{2,10, 2,"Channel Divinity: Guided Strike","Add +10 to an attack roll after seeing the result."},
{2,10, 6,"Channel Divinity: War God's Blessing","Grant an ally within 30 feet +10 to an attack roll as a reaction."},
{2,10, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 damage of the weapon's type, rising to 2d8 at 14th level."},
{2,10,17,"Avatar of Battle","Resistance to nonmagical bludgeoning, piercing and slashing damage."},

/* =============================== druid (3) ============================== */
{3,-1, 1,"Druidic","You know the secret druid language and can leave hidden messages in it."},
{3,-1, 1,"Spellcasting","You cast druid spells using Wisdom, preparing Wisdom modifier + druid level spells each long rest."},
{3,-1, 2,"Wild Shape","Assume the form of a beast you have seen, twice per short or long rest."},
{3,-1, 2,"Druid Circle","Choose the Circle of the Land or the Circle of the Moon."},
{3,-1, 4,"Wild Shape Improvement","You can assume beasts of CR 1/2 without a flying speed."},
{3,-1, 4,"Ability Score Improvement",ASI_TEXT},
{3,-1, 8,"Wild Shape Improvement","You can assume beasts of CR 1."},
{3,-1, 8,"Ability Score Improvement",ASI_TEXT},
{3,-1,12,"Ability Score Improvement",ASI_TEXT},
{3,-1,16,"Ability Score Improvement",ASI_TEXT},
{3,-1,18,"Timeless Body","You age one year for every ten that pass."},
{3,-1,18,"Beast Spells","Cast druid spells while in Wild Shape, without material components."},
{3,-1,19,"Ability Score Improvement",ASI_TEXT},
{3,-1,20,"Archdruid","Unlimited Wild Shape uses; ignore verbal and somatic components of druid spells."},
{3,11, 2,"Bonus Cantrip","Learn one additional druid cantrip."},
{3,11, 2,"Natural Recovery","Recover expended spell slots on a short rest, up to half your druid level."},
{3,11, 3,"Circle Spells","Gain always-prepared spells tied to your chosen land, at 3rd, 5th, 7th and 9th level."},
{3,11, 6,"Land's Stride","Difficult terrain from plants costs no extra movement; advantage on saves against magical plants."},
{3,11,10,"Nature's Ward","Immune to poison and disease; cannot be charmed or frightened by elementals or fey."},
{3,11,14,"Nature's Sanctuary","Beasts and plants must make a Wisdom save to attack you."},
{3,12, 2,"Combat Wild Shape","Wild Shape as a bonus action, and spend spell slots to heal in beast form."},
{3,12, 2,"Circle Forms","Wild Shape into beasts up to CR 1, rising to CR equal to a third of your druid level at 6th."},
{3,12, 6,"Primal Strike","Your beast-form attacks count as magical for overcoming resistance."},
{3,12,10,"Elemental Wild Shape","Spend two Wild Shape uses to become an air, earth, fire or water elemental."},
{3,12,14,"Thousand Forms","You can cast alter self at will."},

/* ============================== fighter (4) ============================== */
{4,-1, 1,"Fighting Style","Choose a fighting style: Archery, Defense, Dueling, Great Weapon Fighting, Protection or Two-Weapon Fighting."},
{4,-1, 1,"Second Wind","As a bonus action, regain 1d10 + fighter level hit points, once per short or long rest."},
{4,-1, 2,"Action Surge","Take one additional action on your turn, once per short or long rest."},
{4,-1, 3,"Martial Archetype","Choose the Champion, Battle Master or Eldritch Knight archetype."},
{4,-1, 4,"Ability Score Improvement",ASI_TEXT},
{4,-1, 5,"Extra Attack","Attack twice when you take the Attack action."},
{4,-1, 6,"Ability Score Improvement",ASI_TEXT},
{4,-1, 8,"Ability Score Improvement",ASI_TEXT},
{4,-1, 9,"Indomitable","Reroll a failed saving throw once per long rest."},
{4,-1,11,"Extra Attack (2)","Attack three times when you take the Attack action."},
{4,-1,12,"Ability Score Improvement",ASI_TEXT},
{4,-1,13,"Indomitable (2 uses)","Use Indomitable twice per long rest."},
{4,-1,14,"Ability Score Improvement",ASI_TEXT},
{4,-1,16,"Ability Score Improvement",ASI_TEXT},
{4,-1,17,"Action Surge (2 uses)","Use Action Surge twice per rest."},
{4,-1,17,"Indomitable (3 uses)","Use Indomitable three times per long rest."},
{4,-1,19,"Ability Score Improvement",ASI_TEXT},
{4,-1,20,"Extra Attack (3)","Attack four times when you take the Attack action."},
{4,13, 3,"Improved Critical","Your weapon attacks score a critical hit on a 19 or 20."},
{4,13, 7,"Remarkable Athlete","Add half your proficiency bonus to Strength, Dexterity and Constitution checks that do not already use it; your running long jump improves."},
{4,13,10,"Additional Fighting Style","Choose a second fighting style."},
{4,13,15,"Superior Critical","Your weapon attacks score a critical hit on an 18 to 20."},
{4,13,18,"Survivor","Regain hit points each turn while above 0 and at or below half your maximum."},
{4,14, 3,"Combat Superiority","Learn three manoeuvres and gain four d8 superiority dice, regained on a short rest."},
{4,14, 3,"Student of War","Gain proficiency with one type of artisan's tools."},
{4,14, 7,"Know Your Enemy","Study a creature for 1 minute to learn how it compares to you."},
{4,14,10,"Improved Combat Superiority","Your superiority dice become d10s."},
{4,14,15,"Improved Combat Superiority","Your superiority dice become d12s."},
{4,14,18,"Relentless","Regain one superiority die when you roll initiative with none left."},
{4,15, 3,"Spellcasting","You learn wizard spells, cast with Intelligence, as a third-caster."},
{4,15, 3,"Weapon Bond","Bond with a weapon; you can summon it to your hand as a bonus action."},
{4,15, 7,"War Magic","After casting a cantrip, make one weapon attack as a bonus action."},
{4,15,10,"Eldritch Strike","A weapon hit gives the target disadvantage on its next save against your spells."},
{4,15,15,"Arcane Charge","Teleport up to 30 feet when you use Action Surge."},
{4,15,18,"Improved War Magic","After casting any spell, make one weapon attack as a bonus action."},

/* =============================== monk (5) =============================== */
{5,-1, 1,"Unarmored Defense","With no armor or shield, your AC equals 10 + Dexterity modifier + Wisdom modifier."},
{5,-1, 1,"Martial Arts","Use Dexterity for monk weapons, roll a martial arts die for damage, and make an unarmed strike as a bonus action."},
{5,-1, 2,"Ki","You have ki points equal to your monk level, regained on a short rest."},
{5,-1, 2,"Unarmored Movement","Your speed increases by 10 feet while unarmored, rising further as you level."},
{5,-1, 3,"Monastic Tradition","Choose the Way of the Open Hand, Way of Shadow or Way of the Four Elements."},
{5,-1, 3,"Deflect Missiles","Reduce ranged weapon damage by 1d10 + Dexterity modifier + monk level as a reaction."},
{5,-1, 4,"Ability Score Improvement",ASI_TEXT},
{5,-1, 4,"Slow Fall","Reduce falling damage by five times your monk level as a reaction."},
{5,-1, 5,"Extra Attack","Attack twice when you take the Attack action."},
{5,-1, 5,"Stunning Strike","Spend 1 ki to stun a creature you hit unless it succeeds on a Constitution save."},
{5,-1, 6,"Ki-Empowered Strikes","Your unarmed strikes count as magical."},
{5,-1, 7,"Evasion","Take no damage on a successful Dexterity save against area effects, and half on a failure."},
{5,-1, 7,"Stillness of Mind","End one effect charming or frightening you as an action."},
{5,-1, 8,"Ability Score Improvement",ASI_TEXT},
{5,-1,10,"Purity of Body","You are immune to disease and poison."},
{5,-1,12,"Ability Score Improvement",ASI_TEXT},
{5,-1,13,"Tongue of the Sun and Moon","You understand and are understood by all speaking creatures."},
{5,-1,14,"Diamond Soul","Proficiency in all saving throws; spend 1 ki to reroll a failed save."},
{5,-1,15,"Timeless Body","You no longer age and need no food or water."},
{5,-1,16,"Ability Score Improvement",ASI_TEXT},
{5,-1,18,"Empty Body","Spend 4 ki to become invisible for 1 minute, or 8 ki to cast astral projection."},
{5,-1,19,"Ability Score Improvement",ASI_TEXT},
{5,-1,20,"Perfect Self","Regain 4 ki points when you roll initiative with none left."},
{5,16, 3,"Open Hand Technique","Flurry of Blows can knock a target prone, push it 15 feet, or deny it reactions."},
{5,16, 6,"Wholeness of Body","Regain hit points equal to three times your monk level, once per long rest."},
{5,16,11,"Tranquility","You gain the effect of a sanctuary spell between long rests."},
{5,16,17,"Quivering Palm","Spend 3 ki to set up lethal vibrations you can trigger within your monk level in days."},
{5,17, 3,"Shadow Arts","Spend 2 ki to cast darkness, darkvision, pass without trace or silence."},
{5,17, 6,"Shadow Step","Teleport 60 feet between areas of dim light or darkness, with advantage on your next melee attack."},
{5,17,11,"Cloak of Shadows","Become invisible in dim light or darkness until you attack or cast a spell."},
{5,17,17,"Opportunist","When a creature within 5 feet is hit by someone else, make a melee attack against it as a reaction."},
{5,18, 3,"Disciple of the Elements","Learn elemental disciplines and spend ki to cast elemental magic."},
{5,18, 6,"Extra Elemental Discipline","Learn an additional elemental discipline."},
{5,18,11,"Extra Elemental Discipline","Learn an additional elemental discipline."},
{5,18,17,"Extra Elemental Discipline","Learn an additional elemental discipline."},

/* ============================== paladin (6) ============================== */
{6,-1, 1,"Divine Sense","Detect celestials, fiends and undead within 60 feet, 1 + Charisma modifier times per long rest."},
{6,-1, 1,"Lay on Hands","A pool of healing equal to five times your paladin level, restored on a long rest."},
{6,-1, 2,"Fighting Style","Choose Defense, Dueling, Great Weapon Fighting or Protection."},
{6,-1, 2,"Spellcasting","You cast paladin spells using Charisma, preparing Charisma modifier + half your paladin level spells."},
{6,-1, 2,"Divine Smite","Expend a spell slot on a melee hit for 2d8 radiant damage, +1d8 per slot level above 1st."},
{6,-1, 3,"Divine Health","You are immune to disease."},
{6,-1, 3,"Sacred Oath","Choose the Oath of Devotion, the Ancients or Vengeance."},
{6,-1, 4,"Ability Score Improvement",ASI_TEXT},
{6,-1, 5,"Extra Attack","Attack twice when you take the Attack action."},
{6,-1, 6,"Aura of Protection","You and allies within 10 feet add your Charisma modifier to saving throws."},
{6,-1, 8,"Ability Score Improvement",ASI_TEXT},
{6,-1,10,"Aura of Courage","You and allies within 10 feet cannot be frightened."},
{6,-1,11,"Improved Divine Smite","Your melee weapon hits deal an extra 1d8 radiant damage."},
{6,-1,12,"Ability Score Improvement",ASI_TEXT},
{6,-1,14,"Cleansing Touch","End a spell on yourself or a willing creature, Charisma modifier times per long rest."},
{6,-1,16,"Ability Score Improvement",ASI_TEXT},
{6,-1,18,"Aura Improvements","Your auras extend to 30 feet."},
{6,-1,19,"Ability Score Improvement",ASI_TEXT},
{6,19, 3,"Channel Divinity: Sacred Weapon","Add your Charisma modifier to attack rolls with a weapon that sheds light."},
{6,19, 3,"Channel Divinity: Turn the Unholy","Turn fiends and undead within 30 feet."},
{6,19, 7,"Aura of Devotion","You and allies within 10 feet cannot be charmed; 30 feet at 18th level."},
{6,19,15,"Purity of Spirit","You are always under the effect of protection from evil and good."},
{6,19,20,"Holy Nimbus","Emanate sunlight for 1 minute, damaging fiends and undead and granting advantage on saves against their spells."},
{6,20, 3,"Channel Divinity: Nature's Wrath","Restrain a creature with spectral vines."},
{6,20, 3,"Channel Divinity: Turn the Faithless","Turn fey and fiends within 30 feet, revealing their true forms."},
{6,20, 7,"Aura of Warding","You and allies within 10 feet have resistance to damage from spells; 30 feet at 18th level."},
{6,20,15,"Undying Sentinel","When reduced to 0 hit points, drop to 1 instead, once per long rest; you stop ageing."},
{6,20,20,"Elder Champion","For 1 minute: regain hit points each turn, cast paladin spells as a bonus action, and foes have disadvantage on saves against your spells."},
{6,21, 3,"Channel Divinity: Abjure Enemy","Frighten and slow a creature that fails a Wisdom save."},
{6,21, 3,"Channel Divinity: Vow of Enmity","Gain advantage on attacks against one creature for 1 minute."},
{6,21, 7,"Relentless Avenger","Move up to half your speed after a successful opportunity attack."},
{6,21,15,"Soul of Vengeance","Make a melee attack as a reaction against a creature bound by your Vow of Enmity."},
{6,21,20,"Avenging Angel","Sprout wings for 1 minute, gaining a 60-foot flying speed and a frightful aura."},

/* =============================== ranger (7) ============================== */
{7,-1, 1,"Favored Enemy","Choose a favored enemy type: advantage on Survival checks to track them and on Intelligence checks to recall lore."},
{7,-1, 1,"Natural Explorer","Choose a favored terrain: travel and foraging benefits, and doubled proficiency on Intelligence and Wisdom checks there."},
{7,-1, 2,"Fighting Style","Choose Archery, Defense, Dueling or Two-Weapon Fighting."},
{7,-1, 2,"Spellcasting","You cast ranger spells using Wisdom."},
{7,-1, 3,"Ranger Archetype","Choose the Hunter or Beast Master archetype."},
{7,-1, 3,"Primeval Awareness","Expend a spell slot to sense favored enemy types within 1 mile."},
{7,-1, 4,"Ability Score Improvement",ASI_TEXT},
{7,-1, 5,"Extra Attack","Attack twice when you take the Attack action."},
{7,-1, 6,"Favored Enemy and Natural Explorer Improvements","Choose an additional favored enemy and terrain."},
{7,-1, 8,"Ability Score Improvement",ASI_TEXT},
{7,-1, 8,"Land's Stride","Difficult nonmagical terrain costs no extra movement; advantage on saves against magical plants."},
{7,-1,10,"Hide in Plain Sight","Spend 1 minute camouflaging yourself for +10 to Stealth checks while you remain still."},
{7,-1,10,"Natural Explorer Improvement","Choose an additional favored terrain."},
{7,-1,12,"Ability Score Improvement",ASI_TEXT},
{7,-1,14,"Vanish","Hide as a bonus action; you cannot be tracked by nonmagical means."},
{7,-1,14,"Favored Enemy Improvement","Choose an additional favored enemy."},
{7,-1,16,"Ability Score Improvement",ASI_TEXT},
{7,-1,18,"Feral Senses","Fight invisible creatures without disadvantage and sense them within 30 feet."},
{7,-1,19,"Ability Score Improvement",ASI_TEXT},
{7,-1,20,"Foe Slayer","Once per turn, add your Wisdom modifier to an attack or damage roll against a favored enemy."},
{7,22, 3,"Hunter's Prey","Choose Colossus Slayer, Giant Killer or Horde Breaker."},
{7,22, 7,"Defensive Tactics","Choose Escape the Horde, Multiattack Defense or Steel Will."},
{7,22,11,"Multiattack","Choose Volley or Whirlwind Attack."},
{7,22,15,"Superior Hunter's Defense","Choose Evasion, Stand Against the Tide or Uncanny Dodge."},
{7,23, 3,"Ranger's Companion","Gain a beast companion of CR 1/4 or lower that obeys your commands."},
{7,23, 7,"Exceptional Training","Your companion can Dash, Disengage, Dodge or Help as a bonus action; its attacks count as magical."},
{7,23,11,"Bestial Fury","Your companion makes two attacks when it takes the Attack action."},
{7,23,15,"Share Spells","Spells you cast on yourself also affect your companion within 30 feet."},

/* =============================== rogue (8) =============================== */
{8,-1, 1,"Expertise","Double your proficiency bonus for two skill or tool proficiencies."},
{8,-1, 1,"Sneak Attack","Deal an extra 1d6 damage to a target you have advantage against, or one adjacent to an ally, rising by 1d6 every odd level."},
{8,-1, 1,"Thieves' Cant","You know a secret mix of dialect, jargon and code."},
{8,-1, 2,"Cunning Action","Dash, Disengage or Hide as a bonus action."},
{8,-1, 3,"Roguish Archetype","Choose the Thief, Assassin or Arcane Trickster archetype."},
{8,-1, 4,"Ability Score Improvement",ASI_TEXT},
{8,-1, 5,"Uncanny Dodge","Halve the damage of one attack you can see, as a reaction."},
{8,-1, 6,"Expertise","Double your proficiency bonus for two more proficiencies."},
{8,-1, 7,"Evasion","Take no damage on a successful Dexterity save against area effects, and half on a failure."},
{8,-1, 8,"Ability Score Improvement",ASI_TEXT},
{8,-1,10,"Ability Score Improvement",ASI_TEXT},
{8,-1,11,"Reliable Talent","Treat a d20 roll of 9 or lower as a 10 for checks using a proficient skill."},
{8,-1,12,"Ability Score Improvement",ASI_TEXT},
{8,-1,14,"Blindsense","Sense hidden or invisible creatures within 10 feet."},
{8,-1,15,"Slippery Mind","Gain proficiency in Wisdom saving throws."},
{8,-1,16,"Ability Score Improvement",ASI_TEXT},
{8,-1,18,"Elusive","No attack roll against you has advantage while you are not incapacitated."},
{8,-1,19,"Ability Score Improvement",ASI_TEXT},
{8,-1,20,"Stroke of Luck","Turn a missed attack into a hit, or a failed check into a 20, once per short or long rest."},
{8,24, 3,"Fast Hands","Use Cunning Action to make a Sleight of Hand check, use thieves' tools or take the Use an Object action."},
{8,24, 3,"Second-Story Work","Climbing costs no extra movement; your running jump distance improves."},
{8,24, 9,"Supreme Sneak","Advantage on Stealth checks if you move no more than half your speed."},
{8,24,13,"Use Magic Device","Ignore class, race and level requirements on magic items."},
{8,24,17,"Thief's Reflexes","Take two turns during the first round of combat."},
{8,25, 3,"Bonus Proficiencies","Gain proficiency with the disguise kit and the poisoner's kit."},
{8,25, 3,"Assassinate","Advantage against creatures that have not acted; hits against surprised creatures are critical."},
{8,25, 9,"Infiltration Expertise","Establish a false identity over seven days and 25 gp."},
{8,25,13,"Impostor","Mimic another creature's speech, writing and behaviour."},
{8,25,17,"Death Strike","Double the damage of an attack against a surprised creature that fails a Constitution save."},
{8,26, 3,"Spellcasting","You learn wizard spells, cast with Intelligence, as a third-caster."},
{8,26, 3,"Mage Hand Legerdemain","Your mage hand is invisible and can pick locks and pockets."},
{8,26, 9,"Magical Ambush","A creature you are hidden from has disadvantage on saves against your spells."},
{8,26,13,"Versatile Trickster","Use mage hand to distract a creature, gaining advantage on attacks against it."},
{8,26,17,"Spell Thief","Steal a spell cast at you for 8 hours, as a reaction, once per long rest."},

/* ============================= sorcerer (9) ============================= */
{9,-1, 1,"Spellcasting","You cast sorcerer spells using Charisma."},
{9,-1, 1,"Sorcerous Origin","Choose the Draconic Bloodline or Wild Magic origin."},
{9,-1, 2,"Font of Magic","You have sorcery points equal to your sorcerer level, convertible to and from spell slots."},
{9,-1, 3,"Metamagic","Choose two Metamagic options to reshape your spells."},
{9,-1, 4,"Ability Score Improvement",ASI_TEXT},
{9,-1, 8,"Ability Score Improvement",ASI_TEXT},
{9,-1,10,"Metamagic","Choose a third Metamagic option."},
{9,-1,12,"Ability Score Improvement",ASI_TEXT},
{9,-1,16,"Ability Score Improvement",ASI_TEXT},
{9,-1,17,"Metamagic","Choose a fourth Metamagic option."},
{9,-1,19,"Ability Score Improvement",ASI_TEXT},
{9,-1,20,"Sorcerous Restoration","Regain 4 sorcery points on a short rest."},
{9,27, 1,"Dragon Ancestor","Choose a dragon type; you speak Draconic and double your proficiency on Charisma checks with dragons."},
{9,27, 1,"Draconic Resilience","Your hit point maximum increases by 1 per sorcerer level, and your unarmored AC is 13 + Dexterity modifier."},
{9,27, 6,"Elemental Affinity","Add your Charisma modifier to damage of your ancestor's type; spend a sorcery point for resistance to it."},
{9,27,14,"Dragon Wings","Sprout wings granting a flying speed equal to your walking speed."},
{9,27,18,"Draconic Presence","Spend 5 sorcery points to charm or frighten creatures within 60 feet."},
{9,28, 1,"Wild Magic Surge","After casting a sorcerer spell of 1st level or higher, a roll of 1 on a d20 triggers a random magical effect."},
{9,28, 1,"Tides of Chaos","Gain advantage on one attack, check or save per long rest."},
{9,28, 6,"Bend Luck","Spend 2 sorcery points to add or subtract 1d4 from another creature's roll."},
{9,28,14,"Controlled Chaos","Roll twice on the Wild Magic table and choose the result."},
{9,28,18,"Spell Bombardment","When you roll maximum on a damage die, roll it again and add the result."},

/* ============================= warlock (10) ============================= */
{10,-1, 1,"Otherworldly Patron","Choose the Archfey, the Fiend or the Great Old One."},
{10,-1, 1,"Pact Magic","You cast warlock spells using Charisma, with slots that recharge on a short rest."},
{10,-1, 2,"Eldritch Invocations","Learn two invocations, gaining more as you level."},
{10,-1, 3,"Pact Boon","Choose the Pact of the Chain, the Blade or the Tome."},
{10,-1, 4,"Ability Score Improvement",ASI_TEXT},
{10,-1, 8,"Ability Score Improvement",ASI_TEXT},
{10,-1,11,"Mystic Arcanum (6th level)","Choose a 6th-level spell to cast once per long rest."},
{10,-1,12,"Ability Score Improvement",ASI_TEXT},
{10,-1,13,"Mystic Arcanum (7th level)","Choose a 7th-level spell to cast once per long rest."},
{10,-1,15,"Mystic Arcanum (8th level)","Choose an 8th-level spell to cast once per long rest."},
{10,-1,16,"Ability Score Improvement",ASI_TEXT},
{10,-1,17,"Mystic Arcanum (9th level)","Choose a 9th-level spell to cast once per long rest."},
{10,-1,19,"Ability Score Improvement",ASI_TEXT},
{10,-1,20,"Eldritch Master","Regain all Pact Magic slots after 1 minute, once per long rest."},
{10,29, 1,"Fey Presence","Charm or frighten creatures in a 10-foot cube as an action, once per short rest."},
{10,29, 6,"Misty Escape","Turn invisible and teleport 60 feet as a reaction to taking damage."},
{10,29,10,"Beguiling Defenses","Immunity to charm; reflect charm attempts back at the caster."},
{10,29,14,"Dark Delirium","Charm or frighten a creature for 1 minute, banishing it to an illusory realm."},
{10,30, 1,"Dark One's Blessing","Gain temporary hit points equal to your Charisma modifier + warlock level when you drop a foe to 0."},
{10,30, 6,"Dark One's Own Luck","Add 1d10 to an ability check or saving throw, once per short rest."},
{10,30,10,"Fiendish Resilience","Choose a damage type to resist after each rest."},
{10,30,14,"Hurl Through Hell","Send a creature you hit through the lower planes for 10d10 psychic damage, once per long rest."},
{10,31, 1,"Awakened Mind","Speak telepathically to any creature within 30 feet."},
{10,31, 6,"Entropic Ward","Impose disadvantage on an attack against you and gain advantage on your next attack, once per short rest."},
{10,31,10,"Thought Shield","Resistance to psychic damage; your thoughts cannot be read."},
{10,31,14,"Create Thrall","Charm an incapacitated humanoid indefinitely and communicate telepathically with it."},

/* ============================== wizard (11) ============================== */
{11,-1, 1,"Spellcasting","You cast wizard spells from your spellbook using Intelligence, preparing Intelligence modifier + wizard level spells."},
{11,-1, 1,"Arcane Recovery","Recover spell slots totalling half your wizard level, rounded up, once per day on a short rest."},
{11,-1, 2,"Arcane Tradition","Choose one of the eight schools of magic."},
{11,-1, 4,"Ability Score Improvement",ASI_TEXT},
{11,-1, 8,"Ability Score Improvement",ASI_TEXT},
{11,-1,12,"Ability Score Improvement",ASI_TEXT},
{11,-1,16,"Ability Score Improvement",ASI_TEXT},
{11,-1,18,"Spell Mastery","Cast one 1st-level and one 2nd-level spell from your spellbook at will."},
{11,-1,19,"Ability Score Improvement",ASI_TEXT},
{11,-1,20,"Signature Spells","Two 3rd-level spells are always prepared and castable once each without a slot."},
{11,32, 2,"Abjuration Savant","Copying abjuration spells into your spellbook costs half the time and gold."},
{11,32, 2,"Arcane Ward","Casting an abjuration spell creates a ward that absorbs damage for you."},
{11,32, 6,"Projected Ward","Your Arcane Ward can absorb damage for a creature within 30 feet."},
{11,32,10,"Improved Abjuration","Add your proficiency bonus to ability checks made as part of abjuration spells."},
{11,32,14,"Spell Resistance","Advantage on saves against spells, and resistance to their damage."},
{11,33, 2,"Conjuration Savant","Copying conjuration spells into your spellbook costs half the time and gold."},
{11,33, 2,"Minor Conjuration","Conjure a nonmagical object of up to 3 feet and 10 pounds."},
{11,33, 6,"Benign Transposition","Teleport 30 feet or swap places with a willing creature."},
{11,33,10,"Focused Conjuration","Your concentration on a conjuration spell cannot be broken by damage."},
{11,33,14,"Durable Summons","Creatures you summon gain 30 temporary hit points."},
{11,34, 2,"Divination Savant","Copying divination spells into your spellbook costs half the time and gold."},
{11,34, 2,"Portent","Roll two d20s after a long rest and replace any attack, check or save with one of them."},
{11,34, 6,"Expert Divination","Casting a divination spell of 2nd level or higher restores a lower-level slot."},
{11,34,10,"The Third Eye","Gain darkvision, ethereal sight, greater comprehension or see invisibility after a rest."},
{11,34,14,"Greater Portent","Roll three d20s for your Portent feature."},
{11,35, 2,"Enchantment Savant","Copying enchantment spells into your spellbook costs half the time and gold."},
{11,35, 2,"Hypnotic Gaze","Charm and incapacitate a creature within 5 feet as an action."},
{11,35, 6,"Instinctive Charm","Redirect an attack against you to another creature, as a reaction."},
{11,35,10,"Split Enchantment","Enchantment spells that target one creature can target a second."},
{11,35,14,"Alter Memories","Make a charmed creature forget it was charmed, and erase up to your Charisma modifier in hours."},
{11,36, 2,"Evocation Savant","Copying evocation spells into your spellbook costs half the time and gold."},
{11,36, 2,"Sculpt Spells","Choose allies to automatically succeed on saves against your evocation spells and take no damage."},
{11,36, 6,"Potent Cantrip","Creatures that succeed on a save against your cantrips still take half damage."},
{11,36,10,"Empowered Evocation","Add your Intelligence modifier to one damage roll of an evocation spell."},
{11,36,14,"Overchannel","Deal maximum damage with a spell of 5th level or lower, at increasing cost to yourself."},
{11,37, 2,"Illusion Savant","Copying illusion spells into your spellbook costs half the time and gold."},
{11,37, 2,"Improved Minor Illusion","Create both a sound and an image with minor illusion."},
{11,37, 6,"Malleable Illusions","Change the nature of an illusion you cast as an action."},
{11,37,10,"Illusory Self","Interpose an illusory duplicate to make an attack miss, once per short rest."},
{11,37,14,"Illusory Reality","Make one object in an illusion real for 1 minute."},
{11,38, 2,"Necromancy Savant","Copying necromancy spells into your spellbook costs half the time and gold."},
{11,38, 2,"Grim Harvest","Regain hit points when you kill a creature with a spell."},
{11,38, 6,"Undead Thralls","Learn animate dead; your undead are tougher and more numerous."},
{11,38,10,"Inured to Undeath","Resistance to necrotic damage; your hit point maximum cannot be reduced."},
{11,38,14,"Command Undead","Take control of an undead creature that fails a Charisma save."},
{11,39, 2,"Transmutation Savant","Copying transmutation spells into your spellbook costs half the time and gold."},
{11,39, 2,"Minor Alchemy","Transform one material into another for 1 hour."},
{11,39, 6,"Transmuter's Stone","Create a stone granting darkvision, speed, proficiency in Constitution saves or a damage resistance."},
{11,39,10,"Shapechanger","Learn polymorph; cast it on yourself without a slot once per short rest."},
{11,39,14,"Master Transmuter","Consume your transmuter's stone to transmute an object, remove curses, restore youth, or grant a major healing."},

/* =========================== artificer (12) ============================ */
/* Tasha's Cauldron of Everything. Specialists: 40 Alchemist, 41 Armorer,
 * 42 Artillerist, 43 Battle Smith. */
{12,-1, 1,"Magical Tinkering","Bestow a minor property on a Tiny nonmagical object: light, a recorded message, an odor or sound, or a visual effect. You may have Intelligence modifier objects so imbued."},
{12,-1, 1,"Spellcasting","You cast artificer spells using Intelligence, through thieves' tools or artisan's tools as a focus, preparing Intelligence modifier + half your artificer level spells."},
{12,-1, 2,"Infuse Item","Learn artificer infusions and imbue nonmagical objects with them after a long rest, turning them into magic items."},
{12,-1, 3,"Artificer Specialist","Choose the Alchemist, Armorer, Artillerist or Battle Smith specialism."},
{12,-1, 3,"The Right Tool for the Job","Spend an hour with thieves' tools or artisan's tools to magically create one set of artisan's tools."},
{12,-1, 4,"Ability Score Improvement",ASI_TEXT},
{12,-1, 6,"Tool Expertise","Double your proficiency bonus for ability checks with tools you are proficient with."},
{12,-1, 7,"Flash of Genius","As a reaction, add your Intelligence modifier to an ability check or saving throw made by you or an ally within 30 feet."},
{12,-1, 8,"Ability Score Improvement",ASI_TEXT},
{12,-1,10,"Magic Item Adept","Attune to four magic items at once, and craft uncommon magic items in a quarter of the time at half the cost."},
{12,-1,11,"Spell-Storing Item","Store a 1st- or 2nd-level artificer spell in an object; it can be cast from the item a number of times equal to twice your Intelligence modifier."},
{12,-1,12,"Ability Score Improvement",ASI_TEXT},
{12,-1,14,"Magic Item Savant","Attune to five magic items at once, and ignore all class, race, spell and level requirements on magic items."},
{12,-1,16,"Ability Score Improvement",ASI_TEXT},
{12,-1,18,"Magic Item Master","Attune to six magic items at once."},
{12,-1,19,"Ability Score Improvement",ASI_TEXT},
{12,-1,20,"Soul of Artifice","+1 to saving throws for each attuned magic item; when reduced to 0 hit points, end one infusion to drop to 1 instead."},
{12,40, 3,"Tool Proficiency","Gain proficiency with alchemist's supplies."},
{12,40, 3,"Experimental Elixir","Create a random elixir after a long rest, or by spending a spell slot: healing, swiftness, resilience, boldness, flight or transformation."},
{12,40, 5,"Alchemical Savant","Add your Intelligence modifier to one roll of any artificer spell that restores hit points or deals acid, fire, necrotic or poison damage."},
{12,40, 9,"Restorative Reagents","Elixirs also grant temporary hit points, and you can cast lesser restoration without a slot once per long rest."},
{12,40,15,"Chemical Mastery","Resistance to acid and poison damage, immunity to the poisoned condition, and you can cast greater restoration and heal once each per long rest."},
{12,41, 3,"Tools of the Trade","Gain proficiency with heavy armor and smith's tools."},
{12,41, 3,"Arcane Armor","Turn a suit of armor into arcane armor that needs no Strength, cannot be removed against your will, and replaces missing limbs."},
{12,41, 3,"Armor Model","Choose the Guardian model (thunder gauntlets and a defensive field) or the Infiltrator model (lightning launcher and stealth benefits)."},
{12,41, 5,"Extra Attack","Attack twice when you take the Attack action."},
{12,41, 9,"Armor Modifications","Your arcane armor counts as separate items for infusions, and you can swap models more quickly."},
{12,41,15,"Perfected Armor","Guardian armor pulls creatures towards you; infiltrator armor makes a struck target vulnerable to your next attack."},
{12,42, 3,"Tool Proficiency","Gain proficiency with woodcarver's tools."},
{12,42, 3,"Eldritch Cannon","Create a Small or Tiny cannon: flamethrower, force ballista or protector."},
{12,42, 5,"Arcane Firearm","Use a wand, staff or rod as an arcane firearm, adding 1d8 to one damage roll of your artificer spells."},
{12,42, 9,"Explosive Cannon","Your cannon deals an extra 1d8 damage and can be detonated for 3d8 force damage."},
{12,42,15,"Fortified Position","Create two cannons at once, and allies gain half cover near them."},
{12,43, 3,"Tool Proficiency","Gain proficiency with smith's tools."},
{12,43, 3,"Battle Ready","Gain proficiency with martial weapons, and use Intelligence for attacks with magic weapons."},
{12,43, 3,"Steel Defender","Build a mechanical companion that fights beside you and can interpose itself to protect an ally."},
{12,43, 5,"Extra Attack","Attack twice when you take the Attack action."},
{12,43, 9,"Arcane Jolt","Once per turn, add 2d6 force damage to a magic weapon hit, or restore that many hit points to a creature within 30 feet."},
{12,43,15,"Improved Defender","Your Arcane Jolt and steel defender grow stronger, and the defender gains a deflecting reaction."},

/* ================== Xanathar's Guide to Everything ===================== */
/* Subclass ids 44-74; see data_subclasses.c for the order. */

{0,44, 3,"Ancestral Protectors","The first creature you hit each rage is hindered: it has disadvantage against anyone but you, and its damage to others is halved."},
{0,44, 6,"Spirit Shield","As a reaction, reduce damage to an ally within 30 feet by 2d6, rising to 3d6 at 10th and 4d6 at 14th level."},
{0,44,10,"Consult the Spirits","Cast augury or clairvoyance without a slot, once per short or long rest."},
{0,44,14,"Vengeful Ancestors","Your Spirit Shield deals the prevented damage back to the attacker as force damage."},
{0,45, 3,"Storm Aura","A 10-foot aura while raging: desert deals fire damage, sea deals lightning to one foe, tundra grants temporary hit points."},
{0,45, 6,"Storm Soul","Resistance to your aura's damage type, plus an environmental benefit."},
{0,45,10,"Shielding Storm","Allies in your aura share your Storm Soul resistance."},
{0,45,14,"Raging Storm","Your aura gains a second effect: restraining, knocking prone, or damaging attackers."},
{0,46, 3,"Divine Fury","Once per turn while raging, deal an extra 1d6 + half your barbarian level necrotic or radiant damage."},
{0,46, 3,"Warrior of the Gods","A spell that restores you to life needs no material components."},
{0,46, 6,"Fanatical Focus","Reroll a failed saving throw once per rage."},
{0,46,10,"Zealous Presence","Grant ten creatures advantage on attacks and saves for one round, once per long rest."},
{0,46,14,"Rage beyond Death","While raging you do not fall unconscious at 0 hit points."},

{1,47, 3,"Mantle of Inspiration","Spend Bardic Inspiration to grant temporary hit points and a free move to several allies."},
{1,47, 3,"Enthralling Performance","Charm up to your Charisma modifier in creatures after a one-minute performance."},
{1,47, 6,"Mantle of Majesty","Cast command as a bonus action each round for one minute, with charmed creatures unable to resist."},
{1,47,14,"Unbreakable Majesty","Foes must save to attack you, and fail their attack if they cannot."},
{1,48, 3,"Bonus Proficiencies","Gain proficiency with medium armor and the scimitar."},
{1,48, 3,"Fighting Style","Choose Dueling or Two-Weapon Fighting."},
{1,48, 3,"Blade Flourish","Your speed increases on a turn you attack, and you can spend Bardic Inspiration on a defensive, slashing or mobile flourish."},
{1,48, 6,"Extra Attack","Attack twice when you take the Attack action."},
{1,48,14,"Master's Flourish","Roll a d6 for a flourish instead of spending Bardic Inspiration."},
{1,49, 3,"Psychic Blades","Spend Bardic Inspiration to deal an extra 2d6 psychic damage, growing with your level."},
{1,49, 3,"Words of Terror","A minute of conversation leaves a creature frightened of you or another for an hour."},
{1,49, 6,"Mantle of Whispers","Capture a dying creature's shadow and wear its identity for an hour."},
{1,49,14,"Shadow Lore","Whisper a dread secret to charm a creature for eight days."},

{2,50, 1,"Bonus Proficiencies","Gain proficiency with heavy armor and smith's tools."},
{2,50, 1,"Blessing of the Forge","Grant a weapon +1 to attack and damage, or armor +1 AC, after a long rest."},
{2,50, 2,"Channel Divinity: Artisan's Blessing","Create a nonmagical metal item worth up to 100 gp in a one-hour ritual."},
{2,50, 6,"Soul of the Forge","+1 AC in heavy armor and resistance to fire damage."},
{2,50, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 fire damage, rising to 2d8 at 14th level."},
{2,50,17,"Saint of Forge and Fire","Immunity to fire damage and resistance to nonmagical weapon damage in heavy armor."},
{2,51, 1,"Circle of Mortality","Healing spells cast on a creature at 0 hit points restore the maximum; you can use spare the dying at 30 feet as a bonus action."},
{2,51, 1,"Eyes of the Grave","Sense undead within 60 feet, Wisdom modifier times per long rest."},
{2,51, 2,"Channel Divinity: Path to the Grave","Curse a creature so the next attack against it has vulnerability to its damage."},
{2,51, 6,"Sentinel at Death's Door","Turn a critical hit against you or an ally into a normal hit, as a reaction."},
{2,51, 8,"Potent Spellcasting","Add your Wisdom modifier to cleric cantrip damage."},
{2,51,17,"Keeper of Souls","When a foe dies nearby, an ally regains hit points equal to its Hit Dice."},

{3,52, 2,"Balm of the Summer Court","A pool of d6s to heal and grant temporary hit points, refreshed on a long rest."},
{3,52, 6,"Hearth of Moonlight and Shadow","Your camp gains protective cover: bonuses to Stealth and Perception, and no light or sound escapes."},
{3,52,10,"Hidden Paths","Teleport 60 feet, or send a willing creature, Wisdom modifier times per long rest."},
{3,52,14,"Walker in Dreams","Cast dream, scrying or teleportation circle after a short rest, once per long rest."},
{3,53, 2,"Speech of the Woods","You learn Sylvan and can speak with beasts."},
{3,53, 2,"Spirit Totem","Summon a bear, hawk or unicorn spirit that heals, aids attacks or bolsters allies."},
{3,53, 6,"Mighty Summoner","Creatures you conjure gain extra hit points and magical attacks."},
{3,53,10,"Guardian Spirit","Summoned creatures near your totem regain hit points each turn."},
{3,53,14,"Faithful Summons","When reduced to 0 hit points, four dire wolves are conjured to defend you."},

{4,54, 3,"Arcane Archer Lore","Gain the Prestidigitation or Druidcraft cantrip and proficiency in Arcana or Nature."},
{4,54, 3,"Arcane Shot","Learn two Arcane Shot options -- banishing, beguiling, bursting, enfeebling, grasping, piercing, seeking or shadow arrow -- used twice per rest."},
{4,54, 7,"Magic Arrow","Your arrows count as magical, and you gain a third Arcane Shot option."},
{4,54, 7,"Curving Shot","Reroll a missed arrow attack against a different target as a bonus action."},
{4,54,15,"Ever-Ready Shot","Regain an Arcane Shot use when you roll initiative with none left."},
{4,54,18,"Arcane Shot Options","You know six Arcane Shot options in all, and their dice increase with level."},
{4,55, 3,"Bonus Proficiency","Gain proficiency in one skill, or with an artisan's tool or a gaming set."},
{4,55, 3,"Born to the Saddle","You mount and dismount cheaply and stay in the saddle when it would throw you."},
{4,55, 3,"Unwavering Mark","Mark a foe you hit; it suffers for attacking others and you can strike back harder."},
{4,55, 7,"Warding Maneuver","As a reaction, add 1d8 to an ally's AC against one attack, and grant resistance if it misses."},
{4,55,10,"Hold the Line","Opportunity attacks stop a creature's movement for the turn."},
{4,55,15,"Ferocious Charger","Knock a creature prone after moving 10 feet in a straight line."},
{4,55,18,"Vigilant Defender","Make an opportunity attack on every other creature's turn."},
{4,56, 3,"Bonus Proficiency","Gain proficiency with one skill or with calligrapher's supplies."},
{4,56, 3,"Fighting Spirit","As a bonus action, gain advantage on weapon attacks this turn and 5 temporary hit points, three times per long rest."},
{4,56, 7,"Elegant Courtier","Add your Wisdom modifier to Persuasion checks and gain proficiency in Wisdom saves."},
{4,56,10,"Tireless Spirit","Regain a use of Fighting Spirit when you roll initiative with none left."},
{4,56,15,"Rapid Strike","Trade advantage on one attack for an extra attack."},
{4,56,18,"Strength before Death","When reduced to 0 hit points, take an extra turn immediately."},

{5,57, 3,"Bonus Proficiencies","Gain proficiency with brewer's supplies and the Performance skill."},
{5,57, 3,"Drunken Technique","Flurry of Blows also grants a Disengage and extra movement."},
{5,57, 6,"Tipsy Sway","Redirect a missed attack to another creature, or stand from prone with 5 feet of movement."},
{5,57,11,"Drunkard's Luck","Spend 2 ki to cancel disadvantage on a roll."},
{5,57,17,"Intoxicated Frenzy","Flurry of Blows grants up to three extra attacks against different targets."},
{5,58, 3,"Path of the Kensei","Choose kensei weapons; gain an AC bonus when wielding them and a ranged bonus attack."},
{5,58, 6,"One with the Blade","Kensei weapons count as magical, and you can spend ki for extra damage."},
{5,58,11,"Sharpen the Blade","Spend up to 3 ki to give a kensei weapon that bonus to attack and damage."},
{5,58,17,"Unerring Accuracy","Reroll a missed monk weapon attack once per turn."},
{5,59, 3,"Radiant Sun Bolt","Make a ranged spell attack for 1d8 radiant damage as part of the Attack action, and spend ki for more."},
{5,59, 6,"Searing Arc Strike","Spend ki to cast burning hands as a bonus action after the Attack action."},
{5,59,11,"Searing Sunburst","Spend ki for a 20-foot sphere of 2d6 radiant damage."},
{5,59,17,"Sun Shield","Shed bright light and answer melee attackers with radiant damage."},

{6,60, 3,"Channel Divinity: Conquering Presence","Frighten creatures within 30 feet that fail a Wisdom save."},
{6,60, 3,"Channel Divinity: Guided Strike","Add +10 to an attack roll after seeing the result."},
{6,60, 7,"Aura of Conquest","Frightened creatures within 10 feet have their speed reduced to 0 and take psychic damage; 30 feet at 18th level."},
{6,60,15,"Scornful Rebuke","Creatures that hit you take psychic damage equal to your Charisma modifier."},
{6,60,20,"Invincible Conqueror","For 1 minute: resistance to all damage, an extra attack, and critical hits on 19-20."},
{6,61, 3,"Channel Divinity: Emissary of Peace","Gain +5 on Persuasion checks for 10 minutes."},
{6,61, 3,"Channel Divinity: Rebuke the Violent","Deal an attacker the damage it dealt to another creature nearby."},
{6,61, 7,"Aura of the Guardian","Take the damage an ally within 10 feet suffers, as a reaction; 30 feet at 18th level."},
{6,61,15,"Protective Spirit","Regain hit points each turn while below half your maximum."},
{6,61,20,"Emissary of Redemption","Resistance to all damage from others, and attackers take radiant damage back."},

{7,62, 3,"Dread Ambusher","+10 initiative, an extra attack on your first turn dealing 1d8 more, and extra speed."},
{7,62, 3,"Umbral Sight","Darkvision 60 feet, and you are invisible to creatures relying on darkvision."},
{7,62, 7,"Iron Mind","Gain proficiency in Wisdom saving throws."},
{7,62,11,"Stalker's Flurry","Make a second attack when you miss, once per turn."},
{7,62,15,"Shadowy Dodge","Impose disadvantage on an attack against you, as a reaction."},
{7,63, 3,"Detect Portal","Sense a planar portal within 1 mile, once per short rest."},
{7,63, 3,"Planar Warrior","Turn your attack's damage into force damage and add 1d8, rising to 2d8 at 11th level."},
{7,63, 7,"Ethereal Step","Cast etherealness for one turn, once per short rest."},
{7,63,11,"Distant Strike","Teleport 10 feet before each attack, and strike a third foe."},
{7,63,15,"Spectral Defense","Halve an attack's damage as a reaction."},
{7,64, 3,"Hunter's Sense","Learn a creature's immunities, resistances and vulnerabilities."},
{7,64, 3,"Slayer's Prey","Mark a quarry to deal an extra 1d6 damage to it each turn."},
{7,64, 7,"Supernatural Defense","Add 1d6 to saves and escape checks against your prey."},
{7,64,11,"Magic-User's Nemesis","Force a nearby caster to fail its spell, once per short rest."},
{7,64,15,"Slayer's Counter","Attack your prey as a reaction when it forces a save, negating the effect on a hit."},

{8,65, 3,"Ear for Deceit","Treat a Wisdom (Insight) roll of 7 or lower as an 8."},
{8,65, 3,"Eye for Detail","Use a bonus action to search for hidden creatures or study a clue."},
{8,65, 3,"Insightful Fighting","Study a creature to gain Sneak Attack against it without advantage."},
{8,65, 9,"Steady Eye","Advantage on Perception and Investigation checks after moving no more than half your speed."},
{8,65,13,"Unerring Eye","Sense illusions and other deceptions within 30 feet."},
{8,65,17,"Eye for Weakness","Insightful Fighting adds 3d6 to your Sneak Attack."},
{8,66, 3,"Master of Intrigue","Gain a disguise kit, forgery kit, gaming set and two languages, and mimic speech."},
{8,66, 3,"Master of Tactics","Use Help as a bonus action, at up to 30 feet."},
{8,66, 9,"Insightful Manipulator","Learn how a creature compares to you after a minute of observation."},
{8,66,13,"Misdirection","Redirect an attack on you to a nearby creature, as a reaction."},
{8,66,17,"Soul of Deceit","Your thoughts cannot be read and you can feed false ones to a reader."},
{8,67, 3,"Skirmisher","Move half your speed as a reaction when an enemy ends its turn near you."},
{8,67, 3,"Survivalist","Gain expertise in Nature and Survival."},
{8,67, 9,"Superior Mobility","Your walking speed increases by 10 feet."},
{8,67,13,"Ambush Master","Advantage on initiative, and allies gain advantage against the first creature you hit."},
{8,67,17,"Sudden Strike","Make a bonus-action attack that can also deal Sneak Attack damage."},
{8,68, 3,"Fancy Footwork","A creature you attack in melee cannot make an opportunity attack against you."},
{8,68, 3,"Rakish Audacity","Add your Charisma modifier to initiative, and use Sneak Attack in a one-on-one duel."},
{8,68, 9,"Panache","Charm or taunt a creature after a successful Persuasion check."},
{8,68,13,"Elegant Maneuver","Gain advantage on your next Acrobatics or Athletics check, as a bonus action."},
{8,68,17,"Master Duelist","Reroll a missed attack with advantage, once per short rest."},

{9,69, 1,"Divine Magic","You can learn cleric spells as sorcerer spells, and you gain one from your divine affinity."},
{9,69, 1,"Favored by the Gods","Add 2d4 to a failed save or missed attack, once per short rest."},
{9,69, 6,"Empowered Healing","Reroll healing dice for yourself or an ally by spending a sorcery point."},
{9,69,14,"Otherworldly Wings","Gain a flying speed of 30 feet as a bonus action."},
{9,69,18,"Unearthly Recovery","Regain half your hit points when below half, once per long rest."},
{9,70, 1,"Eyes of the Dark","Darkvision 120 feet, and you can cast darkness with sorcery points and see through it."},
{9,70, 1,"Strength of the Grave","Make a Charisma save to drop to 1 hit point instead of 0, once per long rest."},
{9,70, 6,"Hound of Ill Omen","Spend sorcery points to summon a dire wolf that hunts one creature."},
{9,70,14,"Shadow Walk","Teleport 120 feet between areas of dim light or darkness, as a bonus action."},
{9,70,18,"Umbral Form","Spend 6 sorcery points to become shadow, gaining resistance to all but force and radiant damage."},
{9,71, 1,"Wind Speaker","You can speak, read and write Primordial and its dialects."},
{9,71, 1,"Tempestuous Magic","Fly 10 feet without provoking attacks, before or after casting a spell of 1st level or higher."},
{9,71, 6,"Heart of the Storm","Deal lightning or thunder damage to nearby creatures when you cast such a spell, and resist both."},
{9,71, 6,"Storm Guide","Stop rain around you, or set the wind's direction."},
{9,71,14,"Storm's Fury","Damage and push a creature that hits you in melee, as a reaction."},
{9,71,18,"Wind Soul","Immunity to lightning and thunder damage, a 60-foot flying speed, and flight you can share."},

{10,72, 1,"Bonus Cantrips","You learn light and sacred flame."},
{10,72, 1,"Healing Light","A pool of d6s equal to 1 + your warlock level to heal creatures within 60 feet."},
{10,72, 6,"Radiant Soul","Resistance to radiant damage, and add your Charisma modifier to one radiant or fire damage roll."},
{10,72,10,"Celestial Resilience","Temporary hit points for you and your allies after every rest."},
{10,72,14,"Searing Vengeance","When you would drop to 0 hit points, rise with half your hit points and blind nearby foes."},
{10,73, 1,"Hexblade's Curse","Curse a creature for extra damage, wider critical hits, and healing when it dies."},
{10,73, 1,"Hex Warrior","Gain medium armor, shields and martial weapons, and use Charisma for one weapon's attacks."},
{10,73, 6,"Accursed Specter","Raise a slain humanoid as a specter under your control until your next long rest."},
{10,73,10,"Armor of Hexes","Impose a 50 percent miss chance on your cursed target's attacks against you."},
{10,73,14,"Master of Hexes","Move your Hexblade's Curse to a new creature when the cursed one dies."},

{11,74, 2,"Arcane Deflection","As a reaction, gain +2 AC against an attack or +4 on a saving throw."},
{11,74, 2,"Tactical Wit","Add your Intelligence modifier to initiative."},
{11,74, 6,"Power Surge","Store surges from dispelled or countered spells and spend one for extra damage."},
{11,74,10,"Durable Magic","+2 to AC and saving throws while concentrating on a spell."},
{11,74,14,"Deflecting Shroud","Arcane Deflection also damages up to three creatures near you."},

/* =================== Tasha's Cauldron of Everything ==================== */
/* Subclass ids 75-100. */

{0,75, 3,"Form of the Beast","Grow a bite that heals you, claws for an extra attack, or a tail that adds to your AC as a reaction."},
{0,75, 6,"Bestial Soul","Your natural weapons count as magical, and you gain swimming, climbing or jumping benefits."},
{0,75,10,"Infectious Fury","Force a creature you hit to attack an ally or take psychic damage."},
{0,75,14,"Call the Hunt","Grant several allies extra damage while you gain temporary hit points."},
{0,76, 3,"Wild Surge","Rolling for rage triggers a random magical effect around you."},
{0,76, 3,"Bolstering Magic","Grant an ally a bonus to attacks and checks, or restore a spell slot."},
{0,76, 6,"Magic Awareness","Detect spells and magic items within 60 feet."},
{0,76,10,"Unstable Backlash","Reroll your Wild Surge as a reaction when you are hit or fail a save."},
{0,76,14,"Controlled Surge","Roll twice on the Wild Magic table and choose the effect."},

{1,77, 3,"Mote of Potential","Your Bardic Inspiration die also damages, heals or shields nearby creatures."},
{1,77, 3,"Performance of Creation","Create a nonmagical item out of song, sized by your bard level."},
{1,77, 6,"Animating Performance","Animate a Large or smaller object as a Dancing Item that fights for you."},
{1,77,14,"Creative Crescendo","Performance of Creation makes several items at once, without a size limit."},
{1,78, 3,"Silver Tongue","Treat a Persuasion or Deception roll of 9 or lower as a 10."},
{1,78, 3,"Unsettling Words","Spend Bardic Inspiration to subtract the die from a creature's next saving throw."},
{1,78, 6,"Unfailing Inspiration","A Bardic Inspiration die that fails to help is not spent."},
{1,78,14,"Infectious Inspiration","When an inspiration die helps, grant another as a reaction."},
{1,78,14,"Universal Speech","Make yourself understood by creatures of your choice for an hour."},

{2,79, 1,"Bonus Proficiencies","Gain heavy armor and proficiency in Intimidation or Persuasion."},
{2,79, 1,"Voice of Authority","When you cast a spell on an ally, it can attack as a reaction."},
{2,79, 2,"Channel Divinity: Order's Demand","Charm creatures within 30 feet and force them to drop what they hold."},
{2,79, 6,"Embodiment of the Law","Cast enchantment spells of 1st level or higher as a bonus action, Wisdom modifier times per long rest."},
{2,79, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 psychic damage, rising to 2d8 at 14th level."},
{2,79,17,"Order's Wrath","A foe you strike takes 2d8 psychic damage when an ally next hits it."},
{2,80, 1,"Implement of Peace","Gain proficiency in Insight, Performance or Persuasion."},
{2,80, 1,"Emboldening Bond","Bind allies so they can add a d4 to attacks, checks and saves while near each other."},
{2,80, 2,"Channel Divinity: Balm of Peace","Move without provoking attacks and heal each creature you pass."},
{2,80, 6,"Protective Bond","A bonded creature can take another's damage and teleport to its side."},
{2,80, 8,"Potent Spellcasting","Add your Wisdom modifier to cleric cantrip damage."},
{2,80,17,"Expansive Bond","Your bond reaches 60 feet and grants resistance to the damage taken for another."},
{2,81, 1,"Bonus Proficiencies","Gain martial weapons and heavy armor."},
{2,81, 1,"Eyes of Night","Darkvision out to 300 feet, which you can share with allies."},
{2,81, 1,"Vigilant Blessing","Grant a creature advantage on its next initiative roll."},
{2,81, 2,"Channel Divinity: Twilight Sanctuary","A 30-foot aura that grants temporary hit points or ends charm and fear each turn."},
{2,81, 6,"Steps of Night","Gain a flying speed in dim light or darkness, as a bonus action."},
{2,81, 8,"Divine Strike","Once per turn, a weapon hit deals an extra 1d8 radiant damage, rising to 2d8 at 14th level."},
{2,81,17,"Twilight Shroud","Your Twilight Sanctuary also grants half cover."},

{3,82, 2,"Halo of Spores","Deal 1d4 necrotic damage to a creature that comes within 10 feet, as a reaction."},
{3,82, 2,"Symbiotic Entity","Spend a Wild Shape use for temporary hit points and doubled spore damage."},
{3,82, 6,"Fungal Infestation","Animate a slain beast or humanoid as a zombie for one hour, as a reaction."},
{3,82,10,"Spreading Spores","Hurl your spores into a 10-foot cube for 10 minutes."},
{3,82,14,"Fungal Body","You cannot be blinded, deafened, frightened or poisoned, and critical hits against you become normal hits."},
{3,83, 2,"Star Map","A map that grants guidance at will and free castings of guiding bolt."},
{3,83, 2,"Starry Form","Spend Wild Shape to take an Archer, Chalice or Dragon constellation form."},
{3,83, 6,"Cosmic Omen","Read an omen after a long rest to add or subtract a d6 from nearby rolls."},
{3,83,10,"Twinkling Constellations","Your constellations improve and you can change form each turn."},
{3,83,14,"Full of Stars","In Starry Form you resist bludgeoning, piercing and slashing damage."},
{3,84, 2,"Summon Wildfire Spirit","Spend a Wild Shape use to summon a wildfire spirit that teleports allies."},
{3,84, 6,"Enhanced Bond","Your fire and healing spells gain 1d8, and can be cast from the spirit."},
{3,84,10,"Cauterizing Flames","When a creature dies nearby, a flame heals or burns whoever enters it."},
{3,84,14,"Blazing Revival","When you drop to 0 hit points, the spirit is consumed to restore half your hit points."},

{4,85, 3,"Psionic Power","A pool of Psionic Energy dice for Protective Field, Psi-Powered Leap and Telekinetic Movement."},
{4,85, 7,"Telekinetic Adept","Move a creature with Psi-Powered Leap, or hurl a foe with Telekinetic Thrust."},
{4,85,10,"Guarded Mind","Resistance to psychic damage, and you can end charm or fear on yourself."},
{4,85,15,"Bulwark of Force","Grant several creatures half cover for one minute, once per long rest."},
{4,85,18,"Telekinetic Master","Cast telekinesis and attack while concentrating on it."},
{4,86, 3,"Bonus Proficiencies","Gain smith's tools and the ability to speak, read and write Giant."},
{4,86, 3,"Rune Carver","Carve giant runes -- cloud, fire, frost, stone, hill or storm -- into your gear."},
{4,86, 3,"Giant's Might","Grow to Large, gain advantage on Strength checks and saves, and deal extra damage."},
{4,86, 7,"Runic Shield","Force an attacker to reroll against an ally, as a reaction."},
{4,86,10,"Great Stature","You grow taller, and Giant's Might deals more damage."},
{4,86,15,"Master of Runes","Invoke each rune twice per rest."},
{4,86,18,"Runic Juggernaut","Giant's Might makes you Huge and adds to your reach."},

{5,87, 3,"Implements of Mercy","Gain Insight, Medicine, a herbalism kit and a mask."},
{5,87, 3,"Hand of Healing","Spend ki to restore hit points in place of a Flurry of Blows attack."},
{5,87, 3,"Hand of Harm","Spend ki to deal extra necrotic damage once per turn."},
{5,87, 6,"Physician's Touch","Your healing also ends a condition; your harm also poisons."},
{5,87,11,"Flurry of Healing and Harm","Flurry of Blows heals without ki, and each strike can harm."},
{5,87,17,"Hand of Ultimate Mercy","Return a creature dead no more than 24 hours to life, once per long rest."},
{5,88, 3,"Arms of the Astral Self","Spectral arms that use Wisdom for unarmed strikes and extend your reach."},
{5,88, 6,"Visage of the Astral Self","A spectral visage granting darkvision, an intimidating gaze and clear speech."},
{5,88,11,"Body of the Astral Self","A full astral body: reduce damage, add force damage, and deliver a deflecting strike."},
{5,88,17,"Awakened Astral Self","Your astral form grants +2 AC and an extra attack."},

{6,89, 3,"Channel Divinity: Peerless Athlete","Advantage on Athletics and Acrobatics, and greater jumps and carrying."},
{6,89, 3,"Channel Divinity: Inspiring Smite","Distribute temporary hit points after a Divine Smite."},
{6,89, 7,"Aura of Alacrity","Your speed increases by 10 feet and allies who come near gain it too."},
{6,89,15,"Glorious Defense","Add your Charisma modifier to an ally's AC and counterattack, as a reaction."},
{6,89,20,"Living Legend","For 1 minute: advantage on Charisma checks, a missed attack turned into a hit, and successful saves."},
{6,90, 3,"Channel Divinity: Watcher's Will","Grant several creatures advantage on Intelligence, Wisdom and Charisma saves."},
{6,90, 3,"Channel Divinity: Abjure the Extraplanar","Turn aberrations, celestials, elementals, fey and fiends."},
{6,90, 7,"Aura of the Sentinel","You and allies within 10 feet add your proficiency bonus to initiative."},
{6,90,15,"Vigilant Rebuke","Deal 2d8 + Charisma force damage to a creature whose spell you resisted."},
{6,90,20,"Mortal Bulwark","Truesight, advantage against extraplanar creatures, and hits that banish them."},

{7,91, 3,"Dreadful Strikes","Deal an extra 1d4 psychic damage once per turn, rising to 1d6 at 11th level."},
{7,91, 3,"Otherworldly Glamour","Add your Wisdom modifier to Charisma checks and gain a social skill."},
{7,91, 7,"Beguiling Twist","Impose disadvantage on charm and fear saves nearby, or redirect the effect."},
{7,91,11,"Fey Reinforcements","Cast summon fey without a slot once per long rest, and it becomes invisible."},
{7,91,15,"Misty Wanderer","Cast misty step without a slot, bringing a companion, Wisdom modifier times per long rest."},
{7,92, 3,"Gathered Swarm","Your swarm moves, damages or shifts a creature you hit once per turn."},
{7,92, 7,"Writhing Tide","Gain a flying speed of 10 feet for one minute, several times per long rest."},
{7,92,11,"Mighty Swarm","Your swarm's damage grows, and it knocks prone or grants half cover."},
{7,92,15,"Swarming Dispersal","Become resistant to damage and teleport 30 feet, as a reaction."},

{8,93, 3,"Whispers of the Dead","Gain any skill or tool proficiency after each rest."},
{8,93, 3,"Wails from the Grave","When you Sneak Attack, deal half as many d6s of necrotic damage to a second creature."},
{8,93, 9,"Tokens of the Departed","Capture a soul trinket that grants advantage on death and Constitution saves."},
{8,93,13,"Ghost Walk","Assume a spectral form with a flying speed that passes through creatures."},
{8,93,17,"Death's Friend","Wails from the Grave triggers every turn, and you gain a soul trinket each rest."},
{8,94, 3,"Psionic Power","Psionic Energy dice powering Psi-Bolstered Knack and Psychic Whispers."},
{8,94, 3,"Psychic Blades","Manifest a psychic blade dealing 1d6 psychic damage, with a bonus-action second blade."},
{8,94, 9,"Soul Blades","Home in on a missed target, or teleport with Psychic Teleportation."},
{8,94,13,"Psychic Veil","Turn invisible for one hour, once per long rest."},
{8,94,17,"Rend Mind","Stun a creature you Sneak Attack for one minute."},

{9,95, 1,"Psionic Spells","Learn psionic spells that need no verbal or somatic components once you can cast them subtly."},
{9,95, 1,"Telepathic Speech","Speak telepathically with a creature for a number of minutes equal to your sorcerer level."},
{9,95, 6,"Psionic Sorcery","Cast psionic spells with sorcery points instead of a slot, and without components."},
{9,95, 6,"Psychic Defenses","Resistance to psychic damage and advantage against being charmed or frightened."},
{9,95,14,"Revelation in Flesh","Spend sorcery points to gain flight, swimming, sight in darkness, or a squeezing body."},
{9,95,18,"Warping Implosion","Teleport 120 feet and pull creatures towards your origin for 3d10 force damage."},
{9,96, 1,"Restore Balance","Cancel a creature's advantage or disadvantage, as a reaction."},
{9,96, 1,"Clockwork Magic","You learn spells of order and protection as you level."},
{9,96, 6,"Bastion of Law","Spend sorcery points to give a creature d8s that ward off damage."},
{9,96,14,"Trance of Order","Attacks against you cannot have advantage, and you treat a d20 roll of 9 or lower as a 10."},
{9,96,18,"Clockwork Cavalcade","Restore hit points, repair objects and end spells in a 30-foot cube."},

{10,97, 1,"Tentacle of the Deeps","Summon a spectral tentacle that deals cold damage and reduces speed."},
{10,97, 1,"Gift of the Sea","You gain a swimming speed of 40 feet and can breathe underwater."},
{10,97, 6,"Oceanic Soul","Resistance to cold damage, and you can speak with any water-breathing creature."},
{10,97, 6,"Guardian Coil","Your tentacle reduces damage to you or a creature it can reach."},
{10,97,10,"Grasping Tentacles","You learn Evard's black tentacles and gain temporary hit points when you cast it."},
{10,97,14,"Fathomless Plunge","Teleport up to six creatures to a coast up to a mile away."},
{10,98, 1,"Genie's Vessel","A vessel you can use as a focus, to rest inside, and to deal bonus elemental damage."},
{10,98, 1,"Expanded Spells","Your genie's kind -- dao, djinni, efreeti or marid -- adds its own spells to your list."},
{10,98, 6,"Elemental Gift","Resistance to your genie's damage type, and a flying speed for 10 minutes."},
{10,98,10,"Sanctuary Vessel","Take up to five companions into your vessel, where they gain the benefit of a short rest."},
{10,98,14,"Limited Wish","Cast any spell of 6th level or lower without components, once per long rest."},

{11,99, 2,"Training in War and Song","Gain light armor, one one-handed melee weapon and proficiency in Performance."},
{11,99, 2,"Bladesong","For 1 minute, gain +Intelligence to AC, +10 speed, advantage on Acrobatics and a concentration bonus."},
{11,99, 6,"Extra Attack","Attack twice, and you can replace one attack with a cantrip."},
{11,99,10,"Song of Defense","Expend a spell slot to reduce damage to you by five times its level."},
{11,99,14,"Song of Victory","Add your Intelligence modifier to melee weapon damage during Bladesong."},
{11,100, 2,"Wizardly Quill","A magical quill that copies spells swiftly and edits your writing."},
{11,100, 2,"Awakened Spellbook","Change a spell's damage type, cast a ritual without preparing it, and reduce copying costs."},
{11,100, 6,"Manifest Mind","Send your spellbook's mind out as a spectral presence to scout and cast from."},
{11,100,10,"Master Scrivener","Create a magic scroll from a spare spellbook after each long rest."},
{11,100,14,"One with the Word","Sacrifice a spell slot to avoid damage; if the book is destroyed you may age instead."},
};
const int FEATURE_COUNT = (int)(sizeof(FEATURES) / sizeof(FEATURES[0]));

/* Ability Score Improvement levels. Every class uses 4/8/12/16/19; the
 * fighter gains two more (6 and 14) and the rogue one more (10). */
int asi_levels_for(int class_id, int out[], int max)
{
    static const int base[] = {4, 8, 12, 16, 19};
    int n = 0, i;

    for (i = 0; i < (int)(sizeof(base) / sizeof(base[0])); i++) {
        if (n < max) out[n++] = base[i];
    }
    if (class_id == 4) {                 /* fighter */
        if (n < max) out[n++] = 6;
        if (n < max) out[n++] = 14;
    } else if (class_id == 8) {          /* rogue */
        if (n < max) out[n++] = 10;
    }
    /* Insertion sort: the list is tiny and must come back ascending. */
    for (i = 1; i < n; i++) {
        int key = out[i], j = i - 1;
        while (j >= 0 && out[j] > key) { out[j + 1] = out[j]; j--; }
        out[j + 1] = key;
    }
    return n;
}
