/* data_backgrounds.c -- PHB chapter 4 backgrounds.
 *
 * Proficiencies, equipment and feature names follow the PHB. The suggested
 * personality traits, ideals, bonds and flaws are brief paraphrases written
 * for this program; the wizard always allows free text instead.
 */
#include "data.h"

const BackgroundData BACKGROUNDS[] = {
{ "Acolyte", BOOK_PHB, {SKL_INSIGHT, SKL_RELIGION}, "", 2,
  "Holy symbol, prayer book or prayer wheel, 5 sticks of incense, "
  "vestments, common clothes", 15,
  "Shelter of the Faithful",
  "You and your companions receive free healing and care at temples of your "
  "faith, and its followers support you at a modest lifestyle.",
  { "I idolise a particular hero of my faith and constantly refer to them.",
    "I can find common ground between the fiercest enemies.",
    "I see omens in every event and action.",
    "Nothing can shake my optimistic attitude.",
    "I quote sacred texts in almost every situation.",
    "I am tolerant of other faiths and respect other gods.", NULL },
  { "Tradition: ancient rituals must be preserved.",
    "Charity: I always try to help those in need.",
    "Change: the gods work in mysterious ways and I embrace it.",
    "Faith: I trust my deity will guide my actions.",
    "Aspiration: I seek to prove myself worthy of my god's favour.", NULL },
  { "I would die to recover an ancient relic of my faith.",
    "I will someday get revenge on the corrupt hierarchy that branded me a heretic.",
    "I owe my life to the priest who took me in as an orphan.",
    "Everything I do is for the common people.",
    "I will do anything to protect the temple where I served.", NULL },
  { "I judge others harshly, and myself even more severely.",
    "I put too much trust in those who wield power in my temple.",
    "My piety sometimes leads me to blindly trust those who profess faith.",
    "I am inflexible in my thinking.",
    "I am suspicious of strangers and expect the worst of them.", NULL } },

{ "Charlatan", BOOK_PHB, {SKL_DECEPTION, SKL_SLEIGHT_OF_HAND},
  "Disguise kit, forgery kit", 0,
  "Fine clothes, disguise kit, tools of the con of your choice", 15,
  "False Identity",
  "You have a second identity with documentation and contacts, and you can "
  "forge documents you have seen.",
  { "I fall in and out of love easily and am always chasing someone.",
    "I have a joke for every occasion, especially where humour is inappropriate.",
    "Flattery is my preferred trick for getting what I want.",
    "I am a born gambler who cannot resist a risk for a potential payoff.",
    "I lie about almost everything, even when there is no reason to.", NULL },
  { "Independence: I am a free spirit and no one tells me what to do.",
    "Fairness: I never target people who cannot afford to lose a few coins.",
    "Charity: I distribute the money I acquire to those who need it.",
    "Creativity: I never run the same con twice.",
    "Friendship: material goods come and go, but bonds last.", NULL },
  { "I fleeced the wrong person and must work to ensure they never find me.",
    "I owe everything to my mentor, a horrible person who is probably rotting in jail.",
    "Somewhere out there I have a child who does not know me.",
    "I come from a noble family and one day I will reclaim my lands and title.",
    "A powerful person killed someone I love; someday I will have my revenge.", NULL },
  { "I cannot resist a pretty face.",
    "I am always in debt; I spend my gains on decadent luxuries.",
    "I am convinced no one could ever fool me the way I fool others.",
    "I am too greedy for my own good.",
    "I cannot resist swindling people more powerful than me.", NULL } },

{ "Criminal", BOOK_PHB, {SKL_DECEPTION, SKL_STEALTH},
  "One type of gaming set, thieves' tools", 0,
  "Crowbar, dark common clothes with a hood", 15,
  "Criminal Contact",
  "You have a reliable contact in the criminal underworld who can carry "
  "messages for you across long distances.",
  { "I always have a plan for what to do when things go wrong.",
    "I am always calm, no matter the situation.",
    "The first thing I do in a new place is note the exits.",
    "I would rather make a new friend than a new enemy.",
    "I blow up at the slightest insult.", NULL },
  { "Honour: I do not steal from others in the trade.",
    "Freedom: chains are meant to be broken.",
    "Charity: I steal from the wealthy to help those in need.",
    "Greed: I will do whatever it takes to become wealthy.",
    "People: I am loyal to my friends, not to ideals.", NULL },
  { "I am trying to pay off an old debt to a generous benefactor.",
    "My ill-gotten gains go to support my family.",
    "Something important was taken from me and I will get it back.",
    "I will become the greatest thief who ever lived.",
    "Someone I loved died because of a mistake I made.", NULL },
  { "When I see something valuable, I cannot think about anything else.",
    "When faced with a choice between money and friends, I usually choose money.",
    "If there is a plan, I will forget it; if I do not, I will ignore it.",
    "I have a tell that reveals when I am lying.",
    "I turn tail and run when things look bad.", NULL } },

{ "Entertainer", BOOK_PHB, {SKL_ACROBATICS, SKL_PERFORMANCE},
  "Disguise kit, one type of musical instrument", 0,
  "A musical instrument, the favour of an admirer, a costume", 15,
  "By Popular Demand",
  "You can always find a place to perform, receiving free lodging and food "
  "of a modest standard in return.",
  { "I know a story relevant to almost every situation.",
    "Whenever I come to a new place, I collect local rumours and gossip.",
    "I am a hopeless romantic, always searching for that special someone.",
    "Nobody stays angry at me for long; I can defuse any tension.",
    "I love a good insult, even one directed at me.", NULL },
  { "Beauty: when I perform, I make the world better than it was.",
    "Tradition: the stories and songs of the past must never be forgotten.",
    "Creativity: the world needs new ideas and bold action.",
    "Honesty: art should reflect the soul and reveal our flaws.",
    "People: I like seeing the smiles on people's faces.", NULL },
  { "My instrument is my most treasured possession.",
    "Someone stole my precious instrument and someday I will get it back.",
    "I want to be famous, whatever it takes.",
    "I idolise a hero of the old tales and measure my deeds against theirs.",
    "I will do anything to prove myself superior to my hated rival.", NULL },
  { "I will do anything to win fame and renown.",
    "I am a sucker for a pretty face.",
    "A scandal prevents me from ever going home again.",
    "I once satirised a noble who still wants my head.",
    "I have trouble keeping my true feelings hidden.", NULL } },

{ "Folk Hero", BOOK_PHB, {SKL_ANIMAL_HANDLING, SKL_SURVIVAL},
  "One type of artisan's tools, vehicles (land)", 0,
  "A set of artisan's tools, a shovel, an iron pot, common clothes", 10,
  "Rustic Hospitality",
  "Common folk shelter you from the law or anyone searching for you, as long "
  "as you do not put them at risk.",
  { "I judge people by their actions, not their words.",
    "If someone is in trouble, I am always ready to lend help.",
    "When I set my mind to something, I follow through no matter what.",
    "I have a strong sense of fair play and always try to find the most "
    "equitable solution.",
    "Thinking is for other people; I prefer action.", NULL },
  { "Respect: people deserve to be treated with dignity.",
    "Fairness: no one should get preferential treatment before the law.",
    "Freedom: tyrants must not be allowed to oppress the people.",
    "Might: if I become strong, I can take what I want.",
    "Destiny: nothing and no one can steer me away from my higher calling.", NULL },
  { "I have a family, but I have no idea where they are.",
    "I worked the land, I love the land, and I will protect the land.",
    "A proud noble once gave me a horrible beating; I will have revenge.",
    "My tools are symbols of my past life and I carry them always.",
    "I protect those who cannot protect themselves.", NULL },
  { "The tyrant who rules my land will stop at nothing to see me killed.",
    "I am convinced of the significance of my destiny and blind to my shortcomings.",
    "The people who knew me when I was young know my shameful secret.",
    "I have a weakness for the vices of the city.",
    "I am inflexible in my thinking.", NULL } },

{ "Guild Artisan", BOOK_PHB, {SKL_INSIGHT, SKL_PERSUASION},
  "One type of artisan's tools", 1,
  "A set of artisan's tools, a letter of introduction from your guild, "
  "traveller's clothes", 15,
  "Guild Membership",
  "Your guild provides lodging and food, supports you politically, and its "
  "members will aid you; dues are 5 gp per month.",
  { "I believe that anything worth doing is worth doing right.",
    "I am well known for my work, and I want to make sure everyone appreciates it.",
    "I have a one-track mind and pursue my goals relentlessly.",
    "I am full of witty aphorisms and have a proverb for every occasion.",
    "I am rude to people who lack my commitment to hard work.", NULL },
  { "Community: it is the duty of all civilised people to strengthen society.",
    "Generosity: my talents were given to me so I could help others.",
    "Freedom: everyone should be free to pursue their livelihood.",
    "Aspiration: I work hard to be the best there is at my craft.",
    "Greed: I am only in it for the money.", NULL },
  { "The workshop where I learned my trade is the most important place to me.",
    "I created a great work for someone and they didn't pay; I still want it.",
    "I owe my guild a great debt for forging me into the person I am.",
    "I pay an exorbitant sum to support my family.",
    "I will get revenge on the evil forces that destroyed my business.", NULL },
  { "I will do anything to get my hands on something rare or priceless.",
    "I am quick to assume that someone is trying to cheat me.",
    "No one must ever learn that I once stole money from guild coffers.",
    "I am never satisfied with what I have; I always want more.",
    "I am horribly jealous of anyone who can outshine my handiwork.", NULL } },

{ "Hermit", BOOK_PHB, {SKL_MEDICINE, SKL_RELIGION}, "Herbalism kit", 1,
  "A scroll case stuffed full of notes, a winter blanket, common clothes, "
  "a herbalism kit", 5,
  "Discovery",
  "Your seclusion gave you a unique and powerful discovery, whose nature you "
  "and your DM determine together.",
  { "I have been isolated for so long that I rarely speak, preferring "
    "gestures and grunts.",
    "I am utterly serene, even in the face of disaster.",
    "The leader of my community had something wise to say on every topic.",
    "I connect everything that happens to me to a grand cosmic plan.",
    "I feel tremendous empathy for all who suffer.", NULL },
  { "Greater Good: my gifts are meant to be shared with all.",
    "Logic: emotions must not cloud our sense of what is right.",
    "Free Thinking: inquiry and curiosity are the pillars of progress.",
    "Self-Knowledge: if you know yourself, there is nothing left to know.",
    "Live and Let Live: meddling in the affairs of others causes trouble.", NULL },
  { "Nothing is more important than the other members of my hermitage.",
    "I entered seclusion because I loved someone I could not have.",
    "I am still seeking the enlightenment I pursued in seclusion.",
    "I entered seclusion to hide from those who might still be hunting me.",
    "My isolation gave me great insight into a great evil that only I can destroy.", NULL },
  { "Now that I have returned to the world, I enjoy its delights a little too much.",
    "I harbour dark, bloodthirsty thoughts that my isolation failed to quell.",
    "I am dogmatic in my thoughts and philosophy.",
    "I let my need to win arguments overshadow friendships.",
    "I would risk too much to uncover a lost bit of knowledge.", NULL } },

{ "Noble", BOOK_PHB, {SKL_HISTORY, SKL_PERSUASION}, "One type of gaming set", 1,
  "Fine clothes, a signet ring, a scroll of pedigree", 25,
  "Position of Privilege",
  "People are inclined to think the best of you; you are welcome in high "
  "society and can secure an audience with local nobles.",
  { "My eloquent flattery makes everyone I talk to feel wonderful.",
    "The common folk love me for my kindness and generosity.",
    "No one could doubt by looking at my regal bearing that I am above the masses.",
    "I take great pains to always look my best and follow the latest fashions.",
    "Despite my noble birth, I do not place myself above other folk.", NULL },
  { "Respect: respect is due to me because of my position.",
    "Responsibility: it is my duty to respect the authority above me.",
    "Independence: I must prove that I can handle myself without coddling.",
    "Power: if I can attain more power, no one will tell me what to do.",
    "Noble Obligation: it is my duty to protect and care for the people beneath me.", NULL },
  { "I will face any challenge to win the approval of my family.",
    "My house's alliance with another noble family must be sustained at all costs.",
    "Nothing is more important than the other members of my family.",
    "I am in love with the heir of a family my family despises.",
    "My loyalty to my sovereign is unwavering.", NULL },
  { "I secretly believe that everyone is beneath me.",
    "I hide a truly scandalous secret that could ruin my family forever.",
    "I too often hear veiled insults and threats in every word.",
    "I have an insatiable desire for carnal pleasures.",
    "In fact, the world does revolve around me.", NULL } },

{ "Outlander", BOOK_PHB, {SKL_ATHLETICS, SKL_SURVIVAL},
  "One type of musical instrument", 1,
  "A staff, a hunting trap, a trophy from an animal you killed, "
  "traveller's clothes", 10,
  "Wanderer",
  "You have an excellent memory for maps and geography, and can find food "
  "and fresh water for yourself and up to five others each day.",
  { "I am driven by a wanderlust that led me away from home.",
    "I watch over my friends as if they were a litter of newborn pups.",
    "I once ran twenty-five miles without stopping to warn my clan; I would do it again.",
    "I have a lesson for every situation, drawn from observing nature.",
    "I place no stock in wealthy or well-mannered folk.", NULL },
  { "Change: life is like the seasons, in constant change.",
    "Greater Good: it is each person's responsibility to make the most happiness.",
    "Honour: if I dishonour myself, I dishonour my whole clan.",
    "Might: the strongest are meant to rule.",
    "Nature: the natural world is more important than the constructs of civilisation.", NULL },
  { "My family, clan or tribe is the most important thing in my life.",
    "An injury to the unspoiled wilderness of my home is an injury to me.",
    "I will bring terrible wrath down on the evildoers who destroyed my homeland.",
    "I am the last of my tribe, and it is up to me to ensure their names endure.",
    "I suffer awful visions of a coming disaster and will do anything to prevent it.", NULL },
  { "I am too enamoured of ale, wine and other intoxicants.",
    "There is no room for caution in a life lived to the fullest.",
    "I remember every insult and nurse a silent resentment.",
    "I am slow to trust members of other races, tribes and societies.",
    "Violence is my answer to almost any challenge.", NULL } },

{ "Sage", BOOK_PHB, {SKL_ARCANA, SKL_HISTORY}, "", 2,
  "A bottle of black ink, a quill, a small knife, a letter from a dead "
  "colleague posing a question you have not yet answered, common clothes", 10,
  "Researcher",
  "When you do not know something, you usually know where and from whom you "
  "can obtain it.",
  { "I use polysyllabic words that convey the impression of erudition.",
    "I have read every book in the world's greatest libraries -- or I would like to.",
    "I am used to helping out those who are not as smart as I am.",
    "There is nothing I like more than a good mystery.",
    "I am willing to listen to every side of an argument before making my own.", NULL },
  { "Knowledge: the path to power and self-improvement is through knowledge.",
    "Beauty: what is beautiful points us beyond itself.",
    "Logic: emotions must not cloud our logical thinking.",
    "No Limits: nothing should fetter the infinite possibility inherent in existence.",
    "Self-Improvement: the goal of a life of study is the betterment of oneself.", NULL },
  { "It is my duty to protect my students.",
    "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.",
    "I work to preserve a library, university, scriptorium or monastery.",
    "My life's work is a series of tomes related to a specific field of lore.",
    "I sold my soul for knowledge; I hope to do great deeds and win it back.", NULL },
  { "I am easily distracted by the promise of information.",
    "Most people scream and run when they see a demon; I stop and take notes.",
    "Unlocking an ancient mystery is worth the price of a civilisation.",
    "I overlook obvious solutions in favour of complicated ones.",
    "I speak without really thinking through my words, invariably insulting others.", NULL } },

{ "Sailor", BOOK_PHB, {SKL_ATHLETICS, SKL_PERCEPTION},
  "Navigator's tools, vehicles (water)", 0,
  "A belaying pin (club), 50 feet of silk rope, a lucky charm, "
  "common clothes", 10,
  "Ship's Passage",
  "You can secure free passage on a sailing ship for yourself and your "
  "companions, in exchange for helping crew the vessel.",
  { "My friends know they can rely on me, no matter what.",
    "I work hard so that I can play hard when the work is done.",
    "I enjoy sailing into new ports and making new friends over a flagon of ale.",
    "I stretch the truth for the sake of a good story.",
    "I never pass up a friendly wager.", NULL },
  { "Respect: the thing that keeps a ship together is mutual respect.",
    "Fairness: we all do the work, so we all share in the rewards.",
    "Freedom: the sea is freedom, to go anywhere and do anything.",
    "Mastery: I am a predator, and the other ships on the sea are my prey.",
    "People: I am committed to my crewmates, not to ideals.", NULL },
  { "I am loyal to my captain first; everything else comes second.",
    "The ship is most important -- crewmates and captains come and go.",
    "I will always remember my first ship.",
    "In a harbour town, I have a paramour whose eyes nearly stole me from the sea.",
    "I was cheated out of my fair share of the profits and I want to get my due.", NULL },
  { "I follow orders, even if I think they are wrong.",
    "I will say anything to avoid having to do extra work.",
    "Once someone questions my courage, I never back down.",
    "I cannot help but pocket loose coins and trinkets I come across.",
    "My pride will probably lead to my destruction.", NULL } },

{ "Soldier", BOOK_PHB, {SKL_ATHLETICS, SKL_INTIMIDATION},
  "One type of gaming set, vehicles (land)", 0,
  "An insignia of rank, a trophy taken from a fallen enemy, a set of bone "
  "dice or deck of cards, common clothes", 10,
  "Military Rank",
  "Soldiers loyal to your former organisation recognise your authority and "
  "defer to you; you can invoke your rank to requisition simple equipment.",
  { "I am always polite and respectful.",
    "I am haunted by memories of war; I cannot get the images out of my mind.",
    "I have lost too many friends and am slow to make new ones.",
    "I am full of inspiring and cautionary tales from my military experience.",
    "I can stare down a hell hound without flinching.", NULL },
  { "Greater Good: our lot is to lay down our lives in defence of others.",
    "Responsibility: I do what I must and obey just authority.",
    "Independence: when people follow orders blindly, they embrace tyranny.",
    "Might: in life as in war, the stronger force wins.",
    "Live and Let Live: ideals are not worth killing over.", NULL },
  { "I would still lay down my life for the people I served with.",
    "Someone saved my life on the battlefield; I will never leave a friend behind.",
    "My honour is my life.",
    "I will never forget the crushing defeat my company suffered.",
    "Those who fight beside me are those worth dying for.", NULL },
  { "The monstrous enemy we faced still leaves me quivering with fear.",
    "I have little respect for anyone who is not a proven warrior.",
    "I made a terrible mistake in battle that cost many lives, and I would do "
    "anything to keep it secret.",
    "My hatred of my enemies is blind and unreasoning.",
    "I obey the law, even if it causes misery.", NULL } },

{ "Urchin", BOOK_PHB, {SKL_SLEIGHT_OF_HAND, SKL_STEALTH},
  "Disguise kit, thieves' tools", 0,
  "A small knife, a map of the city you grew up in, a pet mouse, a token to "
  "remember your parents by, common clothes", 10,
  "City Secrets",
  "You know the secret patterns of cities and can travel between any two "
  "locations at twice the normal speed when not in combat.",
  { "I hide scraps of food and trinkets away in my pockets.",
    "I ask a lot of questions.",
    "I like to squeeze into small places where no one else can get to me.",
    "I sleep with my back to a wall or tree, with everything I own wrapped in a bundle.",
    "I eat like a pig and have bad manners.", NULL },
  { "Respect: all people, rich or poor, deserve respect.",
    "Community: we have to take care of each other, because no one else will.",
    "Change: the low are lifted up and the high brought down; change is the nature of things.",
    "Retribution: the rich need to be shown what life and death are like in the gutters.",
    "People: I help the people who help me -- that is what keeps us alive.", NULL },
  { "My town or city is my home, and I will fight to defend it.",
    "I sponsor an orphanage to keep others from enduring what I did.",
    "I owe my survival to another urchin who taught me to live on the streets.",
    "I escaped my life of poverty by robbing an important person, and I am wanted for it.",
    "No one else should have to endure the hardships I have been through.", NULL },
  { "If I am outnumbered, I will run away from a fight.",
    "Gold seems like a lot of money to me, and I will do just about anything for more of it.",
    "I will never fully trust anyone other than myself.",
    "I would rather kill someone in their sleep than fight fair.",
    "It is not stealing if I need it more than someone else.", NULL } },
};
const int BACKGROUND_COUNT = (int)(sizeof(BACKGROUNDS) / sizeof(BACKGROUNDS[0]));
